/* Fold LTX-2.5's Gemma hidden states into the DiT's conditioning vectors.
 *
 * Between the text tower and the DiT's cross-attention sit two stages. This
 * covers the first: the per-token RMS aggregation that collapses all 49 hidden
 * states into one vector per stream. Three of its details are easy to get
 * wrong in ways that produce a plausible vector rather than an error:
 *
 *   - the RMS is taken per token and per layer over the hidden dimension
 *     alone, not over the concatenated width, and carries no learnable weight;
 *   - the flatten runs [hidden, layer] in row-major order, so the layer index
 *     moves fastest -- concatenating whole layers instead, which is the
 *     intuitive reading, permutes the projection's input; and
 *   - video and audio are rescaled by different factors before their
 *     projections, sqrt(out_features / hidden), so reusing one is wrong for
 *     one of them.
 *
 * Padded tokens are zeroed before the projection rather than after, so their
 * features come out as the projection's bias rather than as zero.
 *
 * The fixture is generated by LTX-2.5's own FeatureExtractorV2, at small
 * dimensions but with the released structure.
 *
 * usage: h3_ltx_conditioning_test FIXTURE.safetensors */

#include "h3_safetensors.h"
#include "h3_weights.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum {
    TOKENS = 8,
    HIDDEN = 12,
    LAYERS = 7,
    VIDEO_DIM = 32,
    AUDIO_DIM = 16,
    CONCAT = HIDDEN * LAYERS
};

#define AGGREGATE_EPS 1e-6f

static int failures = 0;
static h3_weight_store *store = NULL;

static void fail(const char *message) {
    fprintf(stderr, "FAIL: %s\n", message);
    exit(1);
}

static void require(int condition, const char *message) {
    if (!condition) fail(message);
}

static float *load_f32(const char *name, size_t expected) {
    const h3_st_header *header = NULL;
    const h3_st_tensor *tensor = h3_weight_find(store, name, &header);
    if (!tensor || !header) {
        fprintf(stderr, "FAIL: fixture has no tensor %s\n", name);
        exit(1);
    }
    size_t elements = (size_t)h3_st_tensor_elements(tensor);
    if (elements != expected) {
        fprintf(stderr, "FAIL: %s has %zu elements, expected %zu\n",
                name, elements, expected);
        exit(1);
    }
    float *values = malloc(elements * sizeof(*values));
    char error[256];
    require(values != NULL, "cannot allocate a fixture tensor");
    require(h3_st_read_data(header, tensor, values,
                            elements * sizeof(*values), error, sizeof(error)),
            "cannot read a fixture tensor");
    return values;
}

static void compare(const char *label, const float *actual,
                    const float *expected, size_t count, float tolerance) {
    double worst = 0.0;
    size_t worst_at = 0;
    for (size_t index = 0; index < count; index++) {
        /* A non-finite result must fail loudly. Comparing it by magnitude
         * would not: every ordering test against NaN is false, so a NaN slips
         * through as though it were within tolerance. */
        if (!isfinite(actual[index])) {
            fprintf(stderr, "FAIL %-28s produced %f at %zu\n",
                    label, actual[index], index);
            failures++;
            return;
        }
        double delta = fabs((double)actual[index] - (double)expected[index]);
        if (delta > worst) { worst = delta; worst_at = index; }
    }
    if (worst > tolerance) {
        fprintf(stderr, "FAIL %-28s worst |delta| %.3e at %zu (%.8f vs %.8f)\n",
                label, worst, worst_at, actual[worst_at], expected[worst_at]);
        failures++;
    } else {
        printf("  ok  %-28s worst |delta| %.2e\n", label, worst);
    }
}

/* normed[token][d * LAYERS + layer] = hidden[layer][token][d] * rsqrt(mean_d
 * of squares over that token and layer). Padded tokens are zeroed here, which
 * is what leaves their projected features equal to the bias. */
static void aggregate_norm(float *normed, float *const *hidden,
                           const int32_t *mask) {
    for (size_t token = 0; token < TOKENS; token++) {
        if (!mask[token]) {
            memset(normed + token * CONCAT, 0, CONCAT * sizeof(*normed));
            continue;
        }
        for (size_t layer = 0; layer < LAYERS; layer++) {
            const float *row = hidden[layer] + token * HIDDEN;
            float sum = 0.0f;
            for (size_t d = 0; d < HIDDEN; d++) sum += row[d] * row[d];
            float inverse = 1.0f / sqrtf(sum / (float)HIDDEN + AGGREGATE_EPS);
            for (size_t d = 0; d < HIDDEN; d++)
                normed[token * CONCAT + d * LAYERS + layer] = row[d] * inverse;
        }
    }
}

/* Row-major [out, in] weights with a bias, applied to a rescaled input. The
 * rescale is sqrt(out / hidden), which differs between the two streams. */
static void project(float *out, const float *normed, const float *weight,
                    const float *bias, size_t out_dim) {
    float rescale = sqrtf((float)out_dim / (float)HIDDEN);
    for (size_t token = 0; token < TOKENS; token++) {
        for (size_t column = 0; column < out_dim; column++) {
            float sum = bias[column];
            const float *w = weight + column * CONCAT;
            const float *x = normed + token * CONCAT;
            for (size_t k = 0; k < CONCAT; k++)
                sum = fmaf(x[k] * rescale, w[k], sum);
            out[token * out_dim + column] = sum;
        }
    }
}

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s FIXTURE.safetensors\n", argv[0]);
        return 2;
    }
    char error[512];
    store = h3_weight_store_open(argv[1], error, sizeof(error));
    if (!store) {
        fprintf(stderr, "FAIL: cannot open the fixture: %s\n", error);
        return 1;
    }

    printf("LTX-2.5 text aggregation against its own implementation:\n");

    float *hidden[LAYERS];
    for (int layer = 0; layer < LAYERS; layer++) {
        char name[64];
        snprintf(name, sizeof(name), "input.hidden_%d", layer);
        hidden[layer] = load_f32(name, TOKENS * HIDDEN);
    }

    const h3_st_header *mask_header = NULL;
    const h3_st_tensor *mask_tensor = h3_weight_find(store,
                                                     "input.attention_mask",
                                                     &mask_header);
    require(mask_tensor && mask_header, "fixture has no attention mask");
    int32_t mask[TOKENS];
    require(h3_st_read_data(mask_header, mask_tensor, mask, sizeof(mask),
                            error, sizeof(error)),
            "cannot read the attention mask");

    float *normed = malloc((size_t)TOKENS * CONCAT * sizeof(*normed));
    require(normed != NULL, "cannot allocate the aggregation buffer");
    aggregate_norm(normed, hidden, mask);

    float *video_weight = load_f32("video_aggregate_embed.weight",
                                   (size_t)VIDEO_DIM * CONCAT);
    float *video_bias = load_f32("video_aggregate_embed.bias", VIDEO_DIM);
    float *audio_weight = load_f32("audio_aggregate_embed.weight",
                                   (size_t)AUDIO_DIM * CONCAT);
    float *audio_bias = load_f32("audio_aggregate_embed.bias", AUDIO_DIM);

    float *video = malloc((size_t)TOKENS * VIDEO_DIM * sizeof(*video));
    float *audio = malloc((size_t)TOKENS * AUDIO_DIM * sizeof(*audio));
    require(video && audio, "cannot allocate the projected features");
    project(video, normed, video_weight, video_bias, VIDEO_DIM);
    project(audio, normed, audio_weight, audio_bias, AUDIO_DIM);

    float *expected_video = load_f32("reference.video_features",
                                     (size_t)TOKENS * VIDEO_DIM);
    float *expected_audio = load_f32("reference.audio_features",
                                     (size_t)TOKENS * AUDIO_DIM);
    compare("video features", video, expected_video,
            (size_t)TOKENS * VIDEO_DIM, 2e-5f);
    compare("audio features", audio, expected_audio,
            (size_t)TOKENS * AUDIO_DIM, 2e-5f);

    for (int layer = 0; layer < LAYERS; layer++) free(hidden[layer]);
    free(normed); free(video); free(audio);
    free(video_weight); free(video_bias); free(audio_weight); free(audio_bias);
    free(expected_video); free(expected_audio);
    h3_weight_store_free(store);

    if (failures) {
        fprintf(stderr, "\n%d aggregation comparisons failed\n", failures);
        return 1;
    }
    printf("ok: the aggregation reproduces LTX-2.5's own features for both "
           "streams, padded tokens included\n");
    return 0;
}
