/* LTX-2.5's dual-stream DiT block against its own implementation.
 *
 * One block runs eight attentions and two feed-forwards over two streams of
 * different widths and different token counts, coupled in both directions.
 * Most of it is ordinary; these five are not, and each one produces a
 * plausible tensor rather than an error when it is wrong:
 *
 *   - the two cross-modal directions both read the state from *before* either
 *     of them ran. Computing them in sequence, which is the obvious
 *     implementation, feeds audio-to-video's output into video-to-audio and
 *     silently changes the result. Of the four places the reference reads a
 *     snapshot only one can actually differ -- audio-to-video runs first and
 *     touches only the video stream, so video-to-audio's video keys and values
 *     are the load-bearing one and the other three are equal either way;
 *   - the AdaLN triples come out shift, scale, gate for the self-attention and
 *     feed-forward slices, but scale, shift, gate for the cross-modal ones.
 *     The two are the same shape, so swapping them costs nothing at runtime;
 *   - both cross-modal attentions run at the *audio* head width. Video queries
 *     are projected down to 2048 and the result back up to 4096, so the head
 *     dimension is the audio stream's in both directions;
 *   - the text cross-attention takes no rotary embedding at all, while every
 *     other attention here does; and
 *   - modulation is per token, not per step. `timesteps` is nine vectors for
 *     every token, which is a different shape of problem from H3's compact
 *     interpolated table.
 *
 * The query and key norms span the full inner width rather than one head, as
 * they do in the connector and unlike Gemma's. Gating is twice a sigmoid, per
 * head, from the attention's *input*.
 *
 * The fixture is generated by LTX-2.5's own BasicAVTransformerBlock at small
 * dimensions with the released structure: gated attention, cross-attention
 * AdaLN, video feed-forward without bias and audio with.
 *
 * Four of the reference's paths are not exercised, because the fixture leaves
 * them at their defaults, and each will need its own check before a real clip
 * runs: a self-attention mask, a text context mask that is not additive zeros,
 * a perturbation mask below one, and a prompt timestep. The last of those is
 * not hypothetical -- the released checkpoint carries prompt_adaln_single
 * weights, so the key/value modulation may well be timestep-dependent in the
 * real model, and if it is, it stops being cacheable across steps.
 *
 * usage: h3_ltx_dit_block_test FIXTURE.safetensors */

#include "h3_safetensors.h"
#include "h3_weights.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum {
    VIDEO_DIM = 32, VIDEO_HEADS = 4, VIDEO_HEAD = VIDEO_DIM / VIDEO_HEADS,
    AUDIO_DIM = 16, AUDIO_HEADS = 4, AUDIO_HEAD = AUDIO_DIM / AUDIO_HEADS,
    VIDEO_TOKENS = 6, AUDIO_TOKENS = 3, TEXT_TOKENS = 4,
    VIDEO_FF = VIDEO_DIM * 4, AUDIO_FF = AUDIO_DIM * 4,
    /* Nine modulation vectors a token: three for self-attention, three for the
     * feed-forward, three for the text cross-attention. */
    ADA_SLOTS = 9,
    MAX_ROWS = 8, MAX_WIDTH = VIDEO_FF
};

#define BLOCK_EPS 1e-6f

static int failures = 0;
static h3_weight_store *store = NULL;

static void fail(const char *message) {
    fprintf(stderr, "FAIL: %s\n", message);
    exit(1);
}

static void require(int condition, const char *message) {
    if (!condition) fail(message);
}

static float *load_f32(const char *name, size_t expected) {
    const h3_st_header *header = NULL;
    const h3_st_tensor *tensor = h3_weight_find(store, name, &header);
    if (!tensor || !header) {
        fprintf(stderr, "FAIL: fixture has no tensor %s\n", name);
        exit(1);
    }
    size_t elements = (size_t)h3_st_tensor_elements(tensor);
    if (elements != expected) {
        fprintf(stderr, "FAIL: %s has %zu elements, expected %zu\n",
                name, elements, expected);
        exit(1);
    }
    float *values = malloc(elements * sizeof(*values));
    char error[256];
    require(values != NULL, "cannot allocate a fixture tensor");
    require(h3_st_read_data(header, tensor, values,
                            elements * sizeof(*values), error, sizeof(error)),
            "cannot read a fixture tensor");
    return values;
}

static float *load_part(const char *prefix, const char *suffix, size_t expected) {
    char name[192];
    snprintf(name, sizeof(name), "block.%s%s", prefix, suffix);
    return load_f32(name, expected);
}

static void compare(const char *label, const float *actual,
                    const float *expected, size_t count, float tolerance) {
    double worst = 0.0;
    size_t worst_at = 0;
    for (size_t index = 0; index < count; index++) {
        /* A non-finite result must fail loudly. Comparing it by magnitude would
         * not: every ordering test against NaN is false, so a NaN slips through
         * as though it were within tolerance. */
        if (!isfinite(actual[index])) {
            fprintf(stderr, "FAIL %-28s produced %f at %zu\n",
                    label, actual[index], index);
            failures++;
            return;
        }
        double delta = fabs((double)actual[index] - (double)expected[index]);
        if (delta > worst) { worst = delta; worst_at = index; }
    }
    if (worst > tolerance) {
        fprintf(stderr, "FAIL %-28s worst |delta| %.3e at %zu (%.8f vs %.8f)\n",
                label, worst, worst_at, actual[worst_at], expected[worst_at]);
        failures++;
    } else {
        printf("  ok  %-28s worst |delta| %.2e\n", label, worst);
    }
}

/* ------------------------------------------------------------- primitives */

static void linear_bias(float *out, const float *in, const float *weight,
                        const float *bias, size_t rows, size_t input_dim,
                        size_t output_dim) {
    for (size_t row = 0; row < rows; row++) {
        for (size_t column = 0; column < output_dim; column++) {
            float sum = bias ? bias[column] : 0.0f;
            const float *w = weight + column * input_dim;
            const float *x = in + row * input_dim;
            for (size_t k = 0; k < input_dim; k++) sum = fmaf(x[k], w[k], sum);
            out[row * output_dim + column] = sum;
        }
    }
}

/* x * rsqrt(mean(x^2) + eps), optionally scaled. Every norm between the
 * block's residuals is parameter-free; only the query and key norms carry a
 * weight, and those span the full inner width. */
static void rms_norm_rows(float *out, const float *in, const float *weight,
                          size_t rows, size_t width) {
    for (size_t row = 0; row < rows; row++) {
        const float *x = in + row * width;
        float sum = 0.0f;
        for (size_t index = 0; index < width; index++) sum += x[index] * x[index];
        float inverse = 1.0f / sqrtf(sum / (float)width + BLOCK_EPS);
        for (size_t index = 0; index < width; index++) {
            float value = x[index] * inverse;
            out[row * width + index] = weight ? value * weight[index] : value;
        }
    }
}

static float gelu_tanh_value(float value) {
    float cube = value * value * value;
    return 0.5f * value *
           (1.0f + tanhf(0.7978845608028654f * (value + 0.044715f * cube)));
}

/* One AdaLN vector: the block's static table row plus this token's slice of
 * the timestep embedding. `slots` is how many vectors the timestep carries,
 * which is nine for the main table and four or one for the cross-modal ones. */
static void ada_value(float *out, const float *table, const float *timesteps,
                      size_t slots, size_t index, size_t rows, size_t width) {
    for (size_t row = 0; row < rows; row++)
        for (size_t d = 0; d < width; d++)
            out[row * width + d] = table[index * width + d] +
                                   timesteps[row * slots * width + index * width + d];
}

/* rms_norm(x) * (1 + scale) + shift, the block's only normalisation form. */
static void modulate(float *out, const float *in, const float *scale,
                     const float *shift, size_t rows, size_t width) {
    rms_norm_rows(out, in, NULL, rows, width);
    for (size_t row = 0; row < rows; row++)
        for (size_t d = 0; d < width; d++) {
            size_t at = row * width + d;
            out[at] = out[at] * (1.0f + scale[at]) + shift[at];
        }
}

/* Split rotary: the head splits in half and the halves rotate into each other.
 * Tables are [head][token][head_dim / 2], which is the layout the engine's
 * rotary kernel reads with a per-head stride. */
static void apply_rope(float *values, const float *cos_table,
                       const float *sin_table, size_t rows, size_t heads,
                       size_t head_dim) {
    size_t half = head_dim / 2;
    float scratch[MAX_WIDTH];
    for (size_t row = 0; row < rows; row++) {
        for (size_t head = 0; head < heads; head++) {
            float *x = values + (row * heads + head) * head_dim;
            memcpy(scratch, x, head_dim * sizeof(*scratch));
            const float *c = cos_table + (head * rows + row) * half;
            const float *s = sin_table + (head * rows + row) * half;
            for (size_t index = 0; index < half; index++) {
                x[index] = scratch[index] * c[index] - scratch[half + index] * s[index];
                x[half + index] = scratch[half + index] * c[index] +
                                  scratch[index] * s[index];
            }
        }
    }
}

/* --------------------------------------------------------------- attention */

typedef struct {
    size_t query_dim, context_dim, heads, head_dim, inner;
    float *to_q_w, *to_q_b, *to_k_w, *to_k_b, *to_v_w, *to_v_b;
    float *to_out_w, *to_out_b, *q_norm, *k_norm, *gate_w, *gate_b;
} attention;

static attention load_attention(const char *prefix, size_t query_dim,
                                size_t context_dim, size_t heads,
                                size_t head_dim) {
    attention a = {0};
    a.query_dim = query_dim;
    a.context_dim = context_dim;
    a.heads = heads;
    a.head_dim = head_dim;
    a.inner = heads * head_dim;
    a.to_q_w = load_part(prefix, "to_q.weight", a.inner * query_dim);
    a.to_q_b = load_part(prefix, "to_q.bias", a.inner);
    a.to_k_w = load_part(prefix, "to_k.weight", a.inner * context_dim);
    a.to_k_b = load_part(prefix, "to_k.bias", a.inner);
    a.to_v_w = load_part(prefix, "to_v.weight", a.inner * context_dim);
    a.to_v_b = load_part(prefix, "to_v.bias", a.inner);
    a.to_out_w = load_part(prefix, "to_out.0.weight", query_dim * a.inner);
    a.to_out_b = load_part(prefix, "to_out.0.bias", query_dim);
    a.q_norm = load_part(prefix, "q_norm.weight", a.inner);
    a.k_norm = load_part(prefix, "k_norm.weight", a.inner);
    a.gate_w = load_part(prefix, "to_gate_logits.weight", heads * query_dim);
    a.gate_b = load_part(prefix, "to_gate_logits.bias", heads);
    return a;
}

static void free_attention(attention *a) {
    free(a->to_q_w); free(a->to_q_b); free(a->to_k_w); free(a->to_k_b);
    free(a->to_v_w); free(a->to_v_b); free(a->to_out_w); free(a->to_out_b);
    free(a->q_norm); free(a->k_norm); free(a->gate_w); free(a->gate_b);
}

/* Unmasked softmax attention over the whole context. The fixture's context
 * mask is additive zeros, so the masked and unmasked paths agree here and the
 * reference's mask branch is not what this checks. */
static void attend(float *out, const float *query, const float *key,
                   const float *value, size_t rows_q, size_t rows_kv,
                   size_t heads, size_t head_dim) {
    float weights[MAX_ROWS];
    float scale = 1.0f / sqrtf((float)head_dim);
    require(rows_kv <= MAX_ROWS, "reference assumes a short context");
    for (size_t head = 0; head < heads; head++) {
        for (size_t row = 0; row < rows_q; row++) {
            const float *q = query + (row * heads + head) * head_dim;
            float maximum = -INFINITY;
            for (size_t other = 0; other < rows_kv; other++) {
                const float *k = key + (other * heads + head) * head_dim;
                float score = 0.0f;
                for (size_t index = 0; index < head_dim; index++)
                    score = fmaf(q[index], k[index], score);
                weights[other] = score * scale;
                if (weights[other] > maximum) maximum = weights[other];
            }
            float total = 0.0f;
            for (size_t other = 0; other < rows_kv; other++) {
                weights[other] = expf(weights[other] - maximum);
                total += weights[other];
            }
            float *destination = out + (row * heads + head) * head_dim;
            memset(destination, 0, head_dim * sizeof(*destination));
            for (size_t other = 0; other < rows_kv; other++) {
                float share = weights[other] / total;
                const float *v = value + (other * heads + head) * head_dim;
                for (size_t index = 0; index < head_dim; index++)
                    destination[index] = fmaf(share, v[index], destination[index]);
            }
        }
    }
}

/* The Attention module: project, norm the full inner width, rotate, attend,
 * gate per head from the input, project out. `q_cos` NULL is the text
 * cross-attention, which takes no rotary embedding. */
static void run_attention(float *out, const attention *a, const float *x,
                          size_t rows_q, const float *context, size_t rows_kv,
                          const float *q_cos, const float *q_sin,
                          const float *k_cos, const float *k_sin) {
    float query[MAX_ROWS * MAX_WIDTH];
    float key[MAX_ROWS * MAX_WIDTH];
    float value[MAX_ROWS * MAX_WIDTH];
    float heads_out[MAX_ROWS * MAX_WIDTH];

    linear_bias(value, context, a->to_v_w, a->to_v_b, rows_kv,
                a->context_dim, a->inner);
    linear_bias(query, x, a->to_q_w, a->to_q_b, rows_q, a->query_dim, a->inner);
    linear_bias(key, context, a->to_k_w, a->to_k_b, rows_kv,
                a->context_dim, a->inner);
    rms_norm_rows(query, query, a->q_norm, rows_q, a->inner);
    rms_norm_rows(key, key, a->k_norm, rows_kv, a->inner);
    if (q_cos) {
        apply_rope(query, q_cos, q_sin, rows_q, a->heads, a->head_dim);
        apply_rope(key, k_cos ? k_cos : q_cos, k_sin ? k_sin : q_sin,
                   rows_kv, a->heads, a->head_dim);
    }
    attend(heads_out, query, key, value, rows_q, rows_kv, a->heads, a->head_dim);

    /* Twice a sigmoid, so the gates centre on one rather than a half. The
     * logits come from the attention's input, not its output. */
    for (size_t row = 0; row < rows_q; row++) {
        for (size_t head = 0; head < a->heads; head++) {
            float logit = a->gate_b[head];
            const float *w = a->gate_w + head * a->query_dim;
            const float *in = x + row * a->query_dim;
            for (size_t k = 0; k < a->query_dim; k++)
                logit = fmaf(in[k], w[k], logit);
            float gate = 2.0f / (1.0f + expf(-logit));
            float *slot = heads_out + (row * a->heads + head) * a->head_dim;
            for (size_t index = 0; index < a->head_dim; index++)
                slot[index] *= gate;
        }
    }
    linear_bias(out, heads_out, a->to_out_w, a->to_out_b, rows_q,
                a->inner, a->query_dim);
}

/* ------------------------------------------------------------------- block */

/* One stream's static weights and this step's per-token inputs. */
typedef struct {
    size_t dim, tokens, heads, head_dim, ff;
    attention self_attn, text_attn;
    float *scale_shift_table;       /* [9, dim]  */
    float *prompt_scale_shift;      /* [2, dim]  */
    float *ff_in_w, *ff_in_b, *ff_out_w, *ff_out_b;
    float *x, *context, *timesteps;
    float *cross_scale_shift, *cross_gate;
    float *rope_cos, *rope_sin, *cross_rope_cos, *cross_rope_sin;
} stream;

/* Self-attention, then the text cross-attention. Leaves the stream's state in
 * `x` and returns nothing; the cross-modal stage reads `x` afterwards. */
static void run_self_and_text(stream *s) {
    float shift[MAX_ROWS * MAX_WIDTH], scale[MAX_ROWS * MAX_WIDTH];
    float gate[MAX_ROWS * MAX_WIDTH], normed[MAX_ROWS * MAX_WIDTH];
    float attn_out[MAX_ROWS * MAX_WIDTH], modulated[MAX_ROWS * MAX_WIDTH];
    float context[MAX_ROWS * MAX_WIDTH];
    size_t span = s->tokens * s->dim;

    /* Slice 0..3 of the table, in the order shift, scale, gate. */
    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 0, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 1, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 2, s->tokens, s->dim);
    modulate(normed, s->x, scale, shift, s->tokens, s->dim);
    run_attention(attn_out, &s->self_attn, normed, s->tokens, normed, s->tokens,
                  s->rope_cos, s->rope_sin, NULL, NULL);
    for (size_t index = 0; index < span; index++)
        s->x[index] += attn_out[index] * gate[index];
    /* The text cross-attention reads the normalised post-self-attention state,
     * while the residual keeps the unnormalised one. */
    rms_norm_rows(normed, s->x, NULL, s->tokens, s->dim);

    /* Slice 6..9, again shift, scale, gate. */
    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 6, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 7, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 8, s->tokens, s->dim);
    for (size_t index = 0; index < span; index++)
        modulated[index] = normed[index] * (1.0f + scale[index]) + shift[index];
    /* The key/value side is modulated by the static table alone. With the
     * prompt AdaLN MLP disabled there is no timestep term, so the projected
     * text is the same at every denoising step and could be cached. */
    for (size_t token = 0; token < TEXT_TOKENS; token++)
        for (size_t d = 0; d < s->dim; d++)
            context[token * s->dim + d] =
                s->context[token * s->dim + d] *
                    (1.0f + s->prompt_scale_shift[s->dim + d]) +
                s->prompt_scale_shift[d];
    /* No rotary embedding on this one, unlike every other attention here. */
    run_attention(attn_out, &s->text_attn, modulated, s->tokens,
                  context, TEXT_TOKENS, NULL, NULL, NULL, NULL);
    for (size_t index = 0; index < span; index++)
        s->x[index] += attn_out[index] * gate[index];
}

/* The cross-modal AdaLN triple. Note the order: scale before shift, where the
 * self-attention and feed-forward slices give shift before scale. The gate
 * always comes from row four of the table and its own one-vector timestep. */
static void cross_ada(float *scale, float *shift, float *gate,
                      const stream *s, const float *table) {
    ada_value(scale, table, s->cross_scale_shift, 4, 0, s->tokens, s->dim);
    ada_value(shift, table, s->cross_scale_shift, 4, 1, s->tokens, s->dim);
    if (gate) ada_value(gate, table + 4 * s->dim, s->cross_gate, 1, 0,
                        s->tokens, s->dim);
}

static void cross_ada_second(float *scale, float *shift, float *gate,
                             const stream *s, const float *table) {
    ada_value(scale, table, s->cross_scale_shift, 4, 2, s->tokens, s->dim);
    ada_value(shift, table, s->cross_scale_shift, 4, 3, s->tokens, s->dim);
    if (gate) ada_value(gate, table + 4 * s->dim, s->cross_gate, 1, 0,
                        s->tokens, s->dim);
}

static void run_feed_forward(stream *s) {
    float shift[MAX_ROWS * MAX_WIDTH], scale[MAX_ROWS * MAX_WIDTH];
    float gate[MAX_ROWS * MAX_WIDTH], scaled[MAX_ROWS * MAX_WIDTH];
    float inner[MAX_ROWS * MAX_WIDTH], projected[MAX_ROWS * MAX_WIDTH];
    size_t span = s->tokens * s->dim;

    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 3, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 4, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 5, s->tokens, s->dim);
    modulate(scaled, s->x, scale, shift, s->tokens, s->dim);
    /* Plain GELU at four times the width, not a gated pair: the projection's
     * output is the whole of the inner width. */
    linear_bias(inner, scaled, s->ff_in_w, s->ff_in_b, s->tokens, s->dim, s->ff);
    for (size_t index = 0; index < s->tokens * s->ff; index++)
        inner[index] = gelu_tanh_value(inner[index]);
    linear_bias(projected, inner, s->ff_out_w, s->ff_out_b, s->tokens,
                s->ff, s->dim);
    for (size_t index = 0; index < span; index++)
        s->x[index] += projected[index] * gate[index];
}

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s FIXTURE.safetensors\n", argv[0]);
        return 2;
    }
    char error[512];
    store = h3_weight_store_open(argv[1], error, sizeof(error));
    if (!store) {
        fprintf(stderr, "FAIL: cannot open the fixture: %s\n", error);
        return 1;
    }

    printf("LTX-2.5 dual-stream DiT block against its own implementation:\n");

    stream video = {
        .dim = VIDEO_DIM, .tokens = VIDEO_TOKENS,
        .heads = VIDEO_HEADS, .head_dim = VIDEO_HEAD, .ff = VIDEO_FF,
        .self_attn = load_attention("attn1.", VIDEO_DIM, VIDEO_DIM,
                                    VIDEO_HEADS, VIDEO_HEAD),
        .text_attn = load_attention("attn2.", VIDEO_DIM, VIDEO_DIM,
                                    VIDEO_HEADS, VIDEO_HEAD),
        .scale_shift_table = load_f32("block.scale_shift_table",
                                      ADA_SLOTS * VIDEO_DIM),
        .prompt_scale_shift = load_f32("block.prompt_scale_shift_table",
                                       2 * VIDEO_DIM),
        /* The video feed-forward carries no bias; the audio one does. */
        .ff_in_w = load_f32("block.ff.net.0.proj.weight", VIDEO_FF * VIDEO_DIM),
        .ff_in_b = NULL,
        .ff_out_w = load_f32("block.ff.net.2.weight", VIDEO_DIM * VIDEO_FF),
        .ff_out_b = NULL,
        .x = load_f32("input.video_x", VIDEO_TOKENS * VIDEO_DIM),
        .context = load_f32("input.video_context", TEXT_TOKENS * VIDEO_DIM),
        .timesteps = load_f32("input.video_timesteps",
                              VIDEO_TOKENS * ADA_SLOTS * VIDEO_DIM),
        .cross_scale_shift = load_f32("input.video_cross_scale_shift",
                                      VIDEO_TOKENS * 4 * VIDEO_DIM),
        .cross_gate = load_f32("input.video_cross_gate",
                               VIDEO_TOKENS * VIDEO_DIM),
        .rope_cos = load_f32("input.video_rope_cos",
                             VIDEO_HEADS * VIDEO_TOKENS * (VIDEO_HEAD / 2)),
        .rope_sin = load_f32("input.video_rope_sin",
                             VIDEO_HEADS * VIDEO_TOKENS * (VIDEO_HEAD / 2)),
        .cross_rope_cos = load_f32("input.video_cross_rope_cos",
                                   AUDIO_HEADS * VIDEO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_sin = load_f32("input.video_cross_rope_sin",
                                   AUDIO_HEADS * VIDEO_TOKENS * (AUDIO_HEAD / 2)),
    };

    stream audio = {
        .dim = AUDIO_DIM, .tokens = AUDIO_TOKENS,
        .heads = AUDIO_HEADS, .head_dim = AUDIO_HEAD, .ff = AUDIO_FF,
        .self_attn = load_attention("audio_attn1.", AUDIO_DIM, AUDIO_DIM,
                                    AUDIO_HEADS, AUDIO_HEAD),
        .text_attn = load_attention("audio_attn2.", AUDIO_DIM, AUDIO_DIM,
                                    AUDIO_HEADS, AUDIO_HEAD),
        .scale_shift_table = load_f32("block.audio_scale_shift_table",
                                      ADA_SLOTS * AUDIO_DIM),
        .prompt_scale_shift = load_f32("block.audio_prompt_scale_shift_table",
                                       2 * AUDIO_DIM),
        .ff_in_w = load_f32("block.audio_ff.net.0.proj.weight",
                            AUDIO_FF * AUDIO_DIM),
        .ff_in_b = load_f32("block.audio_ff.net.0.proj.bias", AUDIO_FF),
        .ff_out_w = load_f32("block.audio_ff.net.2.weight",
                             AUDIO_DIM * AUDIO_FF),
        .ff_out_b = load_f32("block.audio_ff.net.2.bias", AUDIO_DIM),
        .x = load_f32("input.audio_x", AUDIO_TOKENS * AUDIO_DIM),
        .context = load_f32("input.audio_context", TEXT_TOKENS * AUDIO_DIM),
        .timesteps = load_f32("input.audio_timesteps",
                              AUDIO_TOKENS * ADA_SLOTS * AUDIO_DIM),
        .cross_scale_shift = load_f32("input.audio_cross_scale_shift",
                                      AUDIO_TOKENS * 4 * AUDIO_DIM),
        .cross_gate = load_f32("input.audio_cross_gate",
                               AUDIO_TOKENS * AUDIO_DIM),
        .rope_cos = load_f32("input.audio_rope_cos",
                             AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .rope_sin = load_f32("input.audio_rope_sin",
                             AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_cos = load_f32("input.audio_cross_rope_cos",
                                   AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_sin = load_f32("input.audio_cross_rope_sin",
                                   AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
    };

    /* Both cross-modal attentions run at the audio stream's head width, in
     * both directions: video queries are projected down and the result back
     * up, so the video width appears only at the ends. */
    attention a2v = load_attention("audio_to_video_attn.", VIDEO_DIM, AUDIO_DIM,
                                   AUDIO_HEADS, AUDIO_HEAD);
    attention v2a = load_attention("video_to_audio_attn.", AUDIO_DIM, VIDEO_DIM,
                                   AUDIO_HEADS, AUDIO_HEAD);
    float *a2v_video_table = load_f32("block.scale_shift_table_a2v_ca_video",
                                      5 * VIDEO_DIM);
    float *a2v_audio_table = load_f32("block.scale_shift_table_a2v_ca_audio",
                                      5 * AUDIO_DIM);

    run_self_and_text(&video);
    run_self_and_text(&audio);

    /* Snapshot both streams before either direction runs, so the result does
     * not depend on which direction is computed first. Only one of the four
     * reads below can actually differ from the live state -- video-to-audio's
     * video keys and values, since audio-to-video has by then changed the
     * video stream and nothing has changed the audio one. */
    float video_pre[VIDEO_TOKENS * VIDEO_DIM];
    float audio_pre[AUDIO_TOKENS * AUDIO_DIM];
    memcpy(video_pre, video.x, sizeof(video_pre));
    memcpy(audio_pre, audio.x, sizeof(audio_pre));

    {
        float scale[MAX_ROWS * MAX_WIDTH], shift[MAX_ROWS * MAX_WIDTH];
        float gate[MAX_ROWS * MAX_WIDTH];
        float video_scaled[VIDEO_TOKENS * VIDEO_DIM];
        float audio_scaled[AUDIO_TOKENS * AUDIO_DIM];
        float out[VIDEO_TOKENS * VIDEO_DIM];

        cross_ada(scale, shift, gate, &video, a2v_video_table);
        modulate(video_scaled, video_pre, scale, shift, VIDEO_TOKENS, VIDEO_DIM);
        cross_ada(scale, shift, NULL, &audio, a2v_audio_table);
        modulate(audio_scaled, audio_pre, scale, shift, AUDIO_TOKENS, AUDIO_DIM);
        run_attention(out, &a2v, video_scaled, VIDEO_TOKENS,
                      audio_scaled, AUDIO_TOKENS,
                      video.cross_rope_cos, video.cross_rope_sin,
                      audio.cross_rope_cos, audio.cross_rope_sin);
        for (size_t index = 0; index < VIDEO_TOKENS * VIDEO_DIM; index++)
            video.x[index] += out[index] * gate[index];
    }

    {
        float scale[MAX_ROWS * MAX_WIDTH], shift[MAX_ROWS * MAX_WIDTH];
        float gate[MAX_ROWS * MAX_WIDTH];
        float video_scaled[VIDEO_TOKENS * VIDEO_DIM];
        float audio_scaled[AUDIO_TOKENS * AUDIO_DIM];
        float out[AUDIO_TOKENS * AUDIO_DIM];

        cross_ada_second(scale, shift, gate, &audio, a2v_audio_table);
        modulate(audio_scaled, audio_pre, scale, shift, AUDIO_TOKENS, AUDIO_DIM);
        cross_ada_second(scale, shift, NULL, &video, a2v_video_table);
        modulate(video_scaled, video_pre, scale, shift, VIDEO_TOKENS, VIDEO_DIM);
        run_attention(out, &v2a, audio_scaled, AUDIO_TOKENS,
                      video_scaled, VIDEO_TOKENS,
                      audio.cross_rope_cos, audio.cross_rope_sin,
                      video.cross_rope_cos, video.cross_rope_sin);
        for (size_t index = 0; index < AUDIO_TOKENS * AUDIO_DIM; index++)
            audio.x[index] += out[index] * gate[index];
    }

    run_feed_forward(&video);
    run_feed_forward(&audio);

    float *expected_video = load_f32("reference.video_out",
                                     VIDEO_TOKENS * VIDEO_DIM);
    float *expected_audio = load_f32("reference.audio_out",
                                     AUDIO_TOKENS * AUDIO_DIM);
    /* Eight attentions and two feed-forwards of F32 accumulation land at
     * 1.2e-06 on values around one, so 1e-05 leaves room for a different
     * libm without letting anything structural through. */
    compare("video stream", video.x, expected_video,
            VIDEO_TOKENS * VIDEO_DIM, 1e-5f);
    compare("audio stream", audio.x, expected_audio,
            AUDIO_TOKENS * AUDIO_DIM, 1e-5f);

    free_attention(&video.self_attn); free_attention(&video.text_attn);
    free_attention(&audio.self_attn); free_attention(&audio.text_attn);
    free_attention(&a2v); free_attention(&v2a);
    free(a2v_video_table); free(a2v_audio_table);
    free(expected_video); free(expected_audio);
    h3_weight_store_free(store);

    if (failures) {
        fprintf(stderr, "\n%d block comparisons failed\n", failures);
        return 1;
    }
    printf("ok: the dual-stream block reproduces LTX-2.5's own outputs, "
           "both couplings included\n");
    return 0;
}
