/* Check h3.c's SentencePiece-style tokenizer path against reference ids.
 *
 * LTX-2.5 conditions on Gemma 4, whose tokenizer is not the byte-level BPE
 * that Qwen3-VL uses: spaces become U+2581 through a Replace normalizer, BPE
 * runs over literal codepoints rather than remapped bytes, and anything the
 * vocabulary lacks decomposes into <0xNN> byte-fallback tokens. Reusing the
 * byte-level path would produce plausible but wrong ids, so this compares
 * against ids generated by the reference `tokenizers` library.
 *
 * usage: h3_gemma_tokenizer_test TOKENIZER.json REFERENCE.json
 *
 * REFERENCE.json is an array of {"text": ..., "ids": [...]} objects. Both
 * files are extracted from the published checkpoint, which carries its own
 * tokenizer as a `tokenizer_json` tensor. */

#include "h3_tokenizer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures = 0;

/* The reference file is machine-generated and small, so a scanning reader is
 * enough: find each "text" string, then the "ids" array that follows it. */
static const char *find_key(const char *cursor, const char *key) {
    return cursor ? strstr(cursor, key) : NULL;
}

/* Decode one JSON string literal into a UTF-8 buffer, honouring the \uXXXX,
 * surrogate-pair and short escapes that the generator emits. */
static char *read_json_string(const char **cursor) {
    const char *at = strchr(*cursor, '"');
    if (!at) return NULL;
    at++;
    size_t capacity = strlen(at) + 1;
    char *out = malloc(capacity);
    if (!out) return NULL;
    size_t used = 0;
    while (*at && *at != '"') {
        if (*at != '\\') { out[used++] = *at++; continue; }
        at++;
        switch (*at) {
        case 'n': out[used++] = '\n'; at++; break;
        case 't': out[used++] = '\t'; at++; break;
        case 'r': out[used++] = '\r'; at++; break;
        case 'b': out[used++] = '\b'; at++; break;
        case 'f': out[used++] = '\f'; at++; break;
        case '/': out[used++] = '/';  at++; break;
        case '"': out[used++] = '"';  at++; break;
        case '\\': out[used++] = '\\'; at++; break;
        case 'u': {
            unsigned value = 0;
            if (sscanf(at + 1, "%4x", &value) != 1) { free(out); return NULL; }
            at += 5;
            if (value >= 0xd800 && value <= 0xdbff &&
                at[0] == '\\' && at[1] == 'u') {
                unsigned low = 0;
                if (sscanf(at + 2, "%4x", &low) == 1 &&
                    low >= 0xdc00 && low <= 0xdfff) {
                    value = 0x10000u + ((value - 0xd800u) << 10) +
                            (low - 0xdc00u);
                    at += 6;
                }
            }
            if (value < 0x80) {
                out[used++] = (char)value;
            } else if (value < 0x800) {
                out[used++] = (char)(0xc0 | (value >> 6));
                out[used++] = (char)(0x80 | (value & 0x3f));
            } else if (value < 0x10000) {
                out[used++] = (char)(0xe0 | (value >> 12));
                out[used++] = (char)(0x80 | ((value >> 6) & 0x3f));
                out[used++] = (char)(0x80 | (value & 0x3f));
            } else {
                out[used++] = (char)(0xf0 | (value >> 18));
                out[used++] = (char)(0x80 | ((value >> 12) & 0x3f));
                out[used++] = (char)(0x80 | ((value >> 6) & 0x3f));
                out[used++] = (char)(0x80 | (value & 0x3f));
            }
            break;
        }
        default: free(out); return NULL;
        }
    }
    out[used] = '\0';
    *cursor = *at == '"' ? at + 1 : at;
    return out;
}

static size_t read_ids(const char **cursor, uint32_t *ids, size_t capacity) {
    const char *at = strchr(*cursor, '[');
    if (!at) return (size_t)-1;
    at++;
    size_t used = 0;
    while (*at && *at != ']') {
        if (*at == ' ' || *at == ',' || *at == '\n') { at++; continue; }
        if (used >= capacity) return (size_t)-1;
        char *end = NULL;
        unsigned long value = strtoul(at, &end, 10);
        if (end == at) return (size_t)-1;
        ids[used++] = (uint32_t)value;
        at = end;
    }
    *cursor = *at == ']' ? at + 1 : at;
    return used;
}

static void report(const char *text, const uint32_t *expected,
                   size_t expected_count, const uint32_t *actual,
                   size_t actual_count) {
    fprintf(stderr, "FAIL %-42s\n  expected", text);
    for (size_t index = 0; index < expected_count; index++)
        fprintf(stderr, " %u", expected[index]);
    fprintf(stderr, "\n  actual  ");
    for (size_t index = 0; index < actual_count; index++)
        fprintf(stderr, " %u", actual[index]);
    fprintf(stderr, "\n");
    failures++;
}

int main(int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "usage: %s TOKENIZER.json REFERENCE.json\n", argv[0]);
        return 2;
    }

    char error[512];
    h3_tokenizer *tokenizer = h3_tokenizer_load(argv[1], error, sizeof(error));
    if (!tokenizer) {
        fprintf(stderr, "FAIL: cannot load the Gemma tokenizer: %s\n", error);
        return 1;
    }

    FILE *file = fopen(argv[2], "rb");
    if (!file) {
        fprintf(stderr, "FAIL: cannot open %s\n", argv[2]);
        return 1;
    }
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    fseek(file, 0, SEEK_SET);
    char *json = malloc((size_t)size + 1);
    if (!json || fread(json, 1, (size_t)size, file) != (size_t)size) {
        fprintf(stderr, "FAIL: cannot read %s\n", argv[2]);
        return 1;
    }
    json[size] = '\0';
    fclose(file);

    enum { MAX_IDS = 512 };
    uint32_t expected[MAX_IDS];
    const char *cursor = json;
    size_t cases = 0;

    while ((cursor = find_key(cursor, "\"text\"")) != NULL) {
        cursor += strlen("\"text\"");
        char *text = read_json_string(&cursor);
        if (!text) {
            fprintf(stderr, "FAIL: malformed reference text\n");
            return 1;
        }
        cursor = find_key(cursor, "\"ids\"");
        if (!cursor) {
            fprintf(stderr, "FAIL: reference case has no ids\n");
            return 1;
        }
        cursor += strlen("\"ids\"");
        size_t expected_count = read_ids(&cursor, expected, MAX_IDS);
        if (expected_count == (size_t)-1) {
            fprintf(stderr, "FAIL: malformed reference ids\n");
            return 1;
        }

        uint32_t *actual = NULL;
        size_t actual_count = 0;
        /* pad_empty is off so an empty prompt stays empty, matching the
         * reference call with add_special_tokens=False. */
        if (!h3_tokenizer_encode(tokenizer, text, 0, &actual, &actual_count,
                                 error, sizeof(error))) {
            fprintf(stderr, "FAIL %-42s encode failed: %s\n", text, error);
            failures++;
            free(text);
            continue;
        }
        if (actual_count != expected_count ||
            (expected_count &&
             memcmp(actual, expected, expected_count * sizeof(*expected)))) {
            report(text, expected, expected_count, actual, actual_count);
        } else {
            /* Round-trip every matching case, since a decoder that drops the
             * metaspace substitution would still pass the encode check. */
            char *decoded = h3_tokenizer_decode(tokenizer, actual, actual_count,
                                                error, sizeof(error));
            if (!decoded) {
                fprintf(stderr, "FAIL %-42s decode failed: %s\n", text, error);
                failures++;
            } else if (strcmp(decoded, text) != 0) {
                fprintf(stderr, "FAIL %-42s round trip differs: %s\n",
                        text, decoded);
                failures++;
            }
            free(decoded);
        }
        h3_tokenizer_ids_free(actual);
        free(text);
        cases++;
    }

    free(json);
    h3_tokenizer_free(tokenizer);

    if (!cases) {
        fprintf(stderr, "FAIL: the reference file has no cases\n");
        return 1;
    }
    if (failures) {
        fprintf(stderr, "\n%d of %zu Gemma tokenizer cases failed\n",
                failures, cases);
        return 1;
    }
    printf("ok: %zu cases of %s match the reference ids and round-trip "
           "through decode\n", cases, argv[1]);
    return 0;
}
