/* LTX-2.5's dual-stream DiT block against its own implementation.
 *
 * One block runs eight attentions and two feed-forwards over two streams of
 * different widths and different token counts, coupled in both directions.
 * Most of it is ordinary; these five are not, and each one produces a
 * plausible tensor rather than an error when it is wrong:
 *
 *   - the two cross-modal directions both read the state from *before* either
 *     of them ran. Computing them in sequence, which is the obvious
 *     implementation, feeds audio-to-video's output into video-to-audio and
 *     silently changes the result. Of the four places the reference reads a
 *     snapshot only one can actually differ -- audio-to-video runs first and
 *     touches only the video stream, so video-to-audio's video keys and values
 *     are the load-bearing one and the other three are equal either way;
 *   - the AdaLN triples come out shift, scale, gate for the self-attention and
 *     feed-forward slices, but scale, shift, gate for the cross-modal ones.
 *     The two are the same shape, so swapping them costs nothing at runtime;
 *   - both cross-modal attentions run at the *audio* head width. Video queries
 *     are projected down to 2048 and the result back up to 4096, so the head
 *     dimension is the audio stream's in both directions;
 *   - the text cross-attention takes no rotary embedding at all, while every
 *     other attention here does; and
 *   - modulation is per token, not per step. `timesteps` is nine vectors for
 *     every token, which is a different shape of problem from H3's compact
 *     interpolated table.
 *
 * The query and key norms span the full inner width rather than one head, as
 * they do in the connector and unlike Gemma's. Gating is twice a sigmoid, per
 * head, from the attention's *input*.
 *
 * The fixture is generated by LTX-2.5's own BasicAVTransformerBlock at small
 * dimensions with the released structure: gated attention, cross-attention
 * AdaLN, video feed-forward without bias and audio with.
 *
 * Four of the reference's paths are not exercised, because the fixture leaves
 * them at their defaults, and each will need its own check before a real clip
 * runs: a self-attention mask, a text context mask that is not additive zeros,
 * a perturbation mask below one, and a prompt timestep.
 *
 * The last of those is now settled. `use_prompt_adaln_single` defaults to
 * *true* and the released config does not override it; its weights are present
 * and live, at a standard deviation of 1.9e-02 rather than zero; and the
 * prompt timestep they produce is driven by the modality's scalar sigma, which
 * changes at every denoising step. So the key/value modulation below is
 * timestep-dependent in the released model and is **not** cacheable across
 * steps, the opposite of what the fixture's configuration suggests. The driver
 * must recompute it per step.
 *
 * usage: h3_ltx_dit_block_test FIXTURE.safetensors */

#include "h3_gpu.h"
#include "h3_safetensors.h"
#include "h3_weights.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum {
    VIDEO_DIM = 32, VIDEO_HEADS = 4, VIDEO_HEAD = VIDEO_DIM / VIDEO_HEADS,
    AUDIO_DIM = 16, AUDIO_HEADS = 4, AUDIO_HEAD = AUDIO_DIM / AUDIO_HEADS,
    VIDEO_TOKENS = 6, AUDIO_TOKENS = 3, TEXT_TOKENS = 4,
    VIDEO_FF = VIDEO_DIM * 4, AUDIO_FF = AUDIO_DIM * 4,
    /* Nine modulation vectors a token: three for self-attention, three for the
     * feed-forward, three for the text cross-attention. */
    ADA_SLOTS = 9,
    MAX_ROWS = 8, MAX_WIDTH = VIDEO_FF
};

#define BLOCK_EPS 1e-6f

static int failures = 0;
static h3_weight_store *store = NULL;

static void fail(const char *message) {
    fprintf(stderr, "FAIL: %s\n", message);
    exit(1);
}

static void require(int condition, const char *message) {
    if (!condition) fail(message);
}

static float *load_f32(const char *name, size_t expected) {
    const h3_st_header *header = NULL;
    const h3_st_tensor *tensor = h3_weight_find(store, name, &header);
    if (!tensor || !header) {
        fprintf(stderr, "FAIL: fixture has no tensor %s\n", name);
        exit(1);
    }
    size_t elements = (size_t)h3_st_tensor_elements(tensor);
    if (elements != expected) {
        fprintf(stderr, "FAIL: %s has %zu elements, expected %zu\n",
                name, elements, expected);
        exit(1);
    }
    float *values = malloc(elements * sizeof(*values));
    char error[256];
    require(values != NULL, "cannot allocate a fixture tensor");
    require(h3_st_read_data(header, tensor, values,
                            elements * sizeof(*values), error, sizeof(error)),
            "cannot read a fixture tensor");
    return values;
}

static float *load_part(const char *prefix, const char *suffix, size_t expected) {
    char name[192];
    snprintf(name, sizeof(name), "block.%s%s", prefix, suffix);
    return load_f32(name, expected);
}

static void compare(const char *label, const float *actual,
                    const float *expected, size_t count, float tolerance) {
    double worst = 0.0;
    size_t worst_at = 0;
    for (size_t index = 0; index < count; index++) {
        /* A non-finite result must fail loudly. Comparing it by magnitude would
         * not: every ordering test against NaN is false, so a NaN slips through
         * as though it were within tolerance. */
        if (!isfinite(actual[index])) {
            fprintf(stderr, "FAIL %-28s produced %f at %zu\n",
                    label, actual[index], index);
            failures++;
            return;
        }
        double delta = fabs((double)actual[index] - (double)expected[index]);
        if (delta > worst) { worst = delta; worst_at = index; }
    }
    if (worst > tolerance) {
        fprintf(stderr, "FAIL %-28s worst |delta| %.3e at %zu (%.8f vs %.8f)\n",
                label, worst, worst_at, actual[worst_at], expected[worst_at]);
        failures++;
    } else {
        printf("  ok  %-28s worst |delta| %.2e\n", label, worst);
    }
}

/* ------------------------------------------------------------- primitives */

static void linear_bias(float *out, const float *in, const float *weight,
                        const float *bias, size_t rows, size_t input_dim,
                        size_t output_dim) {
    for (size_t row = 0; row < rows; row++) {
        for (size_t column = 0; column < output_dim; column++) {
            float sum = bias ? bias[column] : 0.0f;
            const float *w = weight + column * input_dim;
            const float *x = in + row * input_dim;
            for (size_t k = 0; k < input_dim; k++) sum = fmaf(x[k], w[k], sum);
            out[row * output_dim + column] = sum;
        }
    }
}

/* x * rsqrt(mean(x^2) + eps), optionally scaled. Every norm between the
 * block's residuals is parameter-free; only the query and key norms carry a
 * weight, and those span the full inner width. */
static void rms_norm_rows(float *out, const float *in, const float *weight,
                          size_t rows, size_t width) {
    for (size_t row = 0; row < rows; row++) {
        const float *x = in + row * width;
        float sum = 0.0f;
        for (size_t index = 0; index < width; index++) sum += x[index] * x[index];
        float inverse = 1.0f / sqrtf(sum / (float)width + BLOCK_EPS);
        for (size_t index = 0; index < width; index++) {
            float value = x[index] * inverse;
            out[row * width + index] = weight ? value * weight[index] : value;
        }
    }
}

static float gelu_tanh_value(float value) {
    float cube = value * value * value;
    return 0.5f * value *
           (1.0f + tanhf(0.7978845608028654f * (value + 0.044715f * cube)));
}

/* One AdaLN vector: the block's static table row plus this token's slice of
 * the timestep embedding. `slots` is how many vectors the timestep carries,
 * which is nine for the main table and four or one for the cross-modal ones. */
static void ada_value(float *out, const float *table, const float *timesteps,
                      size_t slots, size_t index, size_t rows, size_t width) {
    for (size_t row = 0; row < rows; row++)
        for (size_t d = 0; d < width; d++)
            out[row * width + d] = table[index * width + d] +
                                   timesteps[row * slots * width + index * width + d];
}

/* rms_norm(x) * (1 + scale) + shift, the block's only normalisation form. */
static void modulate(float *out, const float *in, const float *scale,
                     const float *shift, size_t rows, size_t width) {
    rms_norm_rows(out, in, NULL, rows, width);
    for (size_t row = 0; row < rows; row++)
        for (size_t d = 0; d < width; d++) {
            size_t at = row * width + d;
            out[at] = out[at] * (1.0f + scale[at]) + shift[at];
        }
}

/* Split rotary: the head splits in half and the halves rotate into each other.
 * Tables are [head][token][head_dim / 2], which is the layout the engine's
 * rotary kernel reads with a per-head stride. */
static void apply_rope(float *values, const float *cos_table,
                       const float *sin_table, size_t rows, size_t heads,
                       size_t head_dim) {
    size_t half = head_dim / 2;
    float scratch[MAX_WIDTH];
    for (size_t row = 0; row < rows; row++) {
        for (size_t head = 0; head < heads; head++) {
            float *x = values + (row * heads + head) * head_dim;
            memcpy(scratch, x, head_dim * sizeof(*scratch));
            const float *c = cos_table + (head * rows + row) * half;
            const float *s = sin_table + (head * rows + row) * half;
            for (size_t index = 0; index < half; index++) {
                x[index] = scratch[index] * c[index] - scratch[half + index] * s[index];
                x[half + index] = scratch[half + index] * c[index] +
                                  scratch[index] * s[index];
            }
        }
    }
}

/* --------------------------------------------------------------- attention */

typedef struct {
    size_t query_dim, context_dim, heads, head_dim, inner;
    float *to_q_w, *to_q_b, *to_k_w, *to_k_b, *to_v_w, *to_v_b;
    float *to_out_w, *to_out_b, *q_norm, *k_norm, *gate_w, *gate_b;
} attention;

static attention load_attention(const char *prefix, size_t query_dim,
                                size_t context_dim, size_t heads,
                                size_t head_dim) {
    attention a = {0};
    a.query_dim = query_dim;
    a.context_dim = context_dim;
    a.heads = heads;
    a.head_dim = head_dim;
    a.inner = heads * head_dim;
    a.to_q_w = load_part(prefix, "to_q.weight", a.inner * query_dim);
    a.to_q_b = load_part(prefix, "to_q.bias", a.inner);
    a.to_k_w = load_part(prefix, "to_k.weight", a.inner * context_dim);
    a.to_k_b = load_part(prefix, "to_k.bias", a.inner);
    a.to_v_w = load_part(prefix, "to_v.weight", a.inner * context_dim);
    a.to_v_b = load_part(prefix, "to_v.bias", a.inner);
    a.to_out_w = load_part(prefix, "to_out.0.weight", query_dim * a.inner);
    a.to_out_b = load_part(prefix, "to_out.0.bias", query_dim);
    a.q_norm = load_part(prefix, "q_norm.weight", a.inner);
    a.k_norm = load_part(prefix, "k_norm.weight", a.inner);
    a.gate_w = load_part(prefix, "to_gate_logits.weight", heads * query_dim);
    a.gate_b = load_part(prefix, "to_gate_logits.bias", heads);
    return a;
}

static void free_attention(attention *a) {
    free(a->to_q_w); free(a->to_q_b); free(a->to_k_w); free(a->to_k_b);
    free(a->to_v_w); free(a->to_v_b); free(a->to_out_w); free(a->to_out_b);
    free(a->q_norm); free(a->k_norm); free(a->gate_w); free(a->gate_b);
}

/* Unmasked softmax attention over the whole context. The fixture's context
 * mask is additive zeros, so the masked and unmasked paths agree here and the
 * reference's mask branch is not what this checks. */
static void attend(float *out, const float *query, const float *key,
                   const float *value, size_t rows_q, size_t rows_kv,
                   size_t heads, size_t head_dim) {
    float weights[MAX_ROWS];
    float scale = 1.0f / sqrtf((float)head_dim);
    require(rows_kv <= MAX_ROWS, "reference assumes a short context");
    for (size_t head = 0; head < heads; head++) {
        for (size_t row = 0; row < rows_q; row++) {
            const float *q = query + (row * heads + head) * head_dim;
            float maximum = -INFINITY;
            for (size_t other = 0; other < rows_kv; other++) {
                const float *k = key + (other * heads + head) * head_dim;
                float score = 0.0f;
                for (size_t index = 0; index < head_dim; index++)
                    score = fmaf(q[index], k[index], score);
                weights[other] = score * scale;
                if (weights[other] > maximum) maximum = weights[other];
            }
            float total = 0.0f;
            for (size_t other = 0; other < rows_kv; other++) {
                weights[other] = expf(weights[other] - maximum);
                total += weights[other];
            }
            float *destination = out + (row * heads + head) * head_dim;
            memset(destination, 0, head_dim * sizeof(*destination));
            for (size_t other = 0; other < rows_kv; other++) {
                float share = weights[other] / total;
                const float *v = value + (other * heads + head) * head_dim;
                for (size_t index = 0; index < head_dim; index++)
                    destination[index] = fmaf(share, v[index], destination[index]);
            }
        }
    }
}

/* The Attention module: project, norm the full inner width, rotate, attend,
 * gate per head from the input, project out. `q_cos` NULL is the text
 * cross-attention, which takes no rotary embedding. */
static void run_attention(float *out, const attention *a, const float *x,
                          size_t rows_q, const float *context, size_t rows_kv,
                          const float *q_cos, const float *q_sin,
                          const float *k_cos, const float *k_sin) {
    float query[MAX_ROWS * MAX_WIDTH];
    float key[MAX_ROWS * MAX_WIDTH];
    float value[MAX_ROWS * MAX_WIDTH];
    float heads_out[MAX_ROWS * MAX_WIDTH];

    linear_bias(value, context, a->to_v_w, a->to_v_b, rows_kv,
                a->context_dim, a->inner);
    linear_bias(query, x, a->to_q_w, a->to_q_b, rows_q, a->query_dim, a->inner);
    linear_bias(key, context, a->to_k_w, a->to_k_b, rows_kv,
                a->context_dim, a->inner);
    rms_norm_rows(query, query, a->q_norm, rows_q, a->inner);
    rms_norm_rows(key, key, a->k_norm, rows_kv, a->inner);
    if (q_cos) {
        apply_rope(query, q_cos, q_sin, rows_q, a->heads, a->head_dim);
        apply_rope(key, k_cos ? k_cos : q_cos, k_sin ? k_sin : q_sin,
                   rows_kv, a->heads, a->head_dim);
    }
    attend(heads_out, query, key, value, rows_q, rows_kv, a->heads, a->head_dim);

    /* Twice a sigmoid, so the gates centre on one rather than a half. The
     * logits come from the attention's input, not its output. */
    for (size_t row = 0; row < rows_q; row++) {
        for (size_t head = 0; head < a->heads; head++) {
            float logit = a->gate_b[head];
            const float *w = a->gate_w + head * a->query_dim;
            const float *in = x + row * a->query_dim;
            for (size_t k = 0; k < a->query_dim; k++)
                logit = fmaf(in[k], w[k], logit);
            float gate = 2.0f / (1.0f + expf(-logit));
            float *slot = heads_out + (row * a->heads + head) * a->head_dim;
            for (size_t index = 0; index < a->head_dim; index++)
                slot[index] *= gate;
        }
    }
    linear_bias(out, heads_out, a->to_out_w, a->to_out_b, rows_q,
                a->inner, a->query_dim);
}

/* ------------------------------------------------------------------- block */

/* One stream's static weights and this step's per-token inputs. */
typedef struct {
    size_t dim, tokens, heads, head_dim, ff;
    attention self_attn, text_attn;
    float *scale_shift_table;       /* [9, dim]  */
    float *prompt_scale_shift;      /* [2, dim]  */
    float *ff_in_w, *ff_in_b, *ff_out_w, *ff_out_b;
    float *x, *context, *timesteps;
    float *cross_scale_shift, *cross_gate;
    float *rope_cos, *rope_sin, *cross_rope_cos, *cross_rope_sin;
} stream;

/* Self-attention, then the text cross-attention. Leaves the stream's state in
 * `x` and returns nothing; the cross-modal stage reads `x` afterwards. */
static void run_self_and_text(stream *s) {
    float shift[MAX_ROWS * MAX_WIDTH], scale[MAX_ROWS * MAX_WIDTH];
    float gate[MAX_ROWS * MAX_WIDTH], normed[MAX_ROWS * MAX_WIDTH];
    float attn_out[MAX_ROWS * MAX_WIDTH], modulated[MAX_ROWS * MAX_WIDTH];
    float context[MAX_ROWS * MAX_WIDTH];
    size_t span = s->tokens * s->dim;

    /* Slice 0..3 of the table, in the order shift, scale, gate. */
    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 0, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 1, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 2, s->tokens, s->dim);
    modulate(normed, s->x, scale, shift, s->tokens, s->dim);
    run_attention(attn_out, &s->self_attn, normed, s->tokens, normed, s->tokens,
                  s->rope_cos, s->rope_sin, NULL, NULL);
    for (size_t index = 0; index < span; index++)
        s->x[index] += attn_out[index] * gate[index];
    /* The text cross-attention reads the normalised post-self-attention state,
     * while the residual keeps the unnormalised one. */
    rms_norm_rows(normed, s->x, NULL, s->tokens, s->dim);

    /* Slice 6..9, again shift, scale, gate. */
    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 6, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 7, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 8, s->tokens, s->dim);
    for (size_t index = 0; index < span; index++)
        modulated[index] = normed[index] * (1.0f + scale[index]) + shift[index];
    /* The key/value side is modulated by the static table alone, because this
     * fixture has no prompt timestep. The released model does -- see the
     * header -- so the driver adds a per-step term here rather than caching. */
    for (size_t token = 0; token < TEXT_TOKENS; token++)
        for (size_t d = 0; d < s->dim; d++)
            context[token * s->dim + d] =
                s->context[token * s->dim + d] *
                    (1.0f + s->prompt_scale_shift[s->dim + d]) +
                s->prompt_scale_shift[d];
    /* No rotary embedding on this one, unlike every other attention here. */
    run_attention(attn_out, &s->text_attn, modulated, s->tokens,
                  context, TEXT_TOKENS, NULL, NULL, NULL, NULL);
    for (size_t index = 0; index < span; index++)
        s->x[index] += attn_out[index] * gate[index];
}

/* The cross-modal AdaLN triple. Note the order: scale before shift, where the
 * self-attention and feed-forward slices give shift before scale. The gate
 * always comes from row four of the table and its own one-vector timestep. */
static void cross_ada(float *scale, float *shift, float *gate,
                      const stream *s, const float *table) {
    ada_value(scale, table, s->cross_scale_shift, 4, 0, s->tokens, s->dim);
    ada_value(shift, table, s->cross_scale_shift, 4, 1, s->tokens, s->dim);
    if (gate) ada_value(gate, table + 4 * s->dim, s->cross_gate, 1, 0,
                        s->tokens, s->dim);
}

static void cross_ada_second(float *scale, float *shift, float *gate,
                             const stream *s, const float *table) {
    ada_value(scale, table, s->cross_scale_shift, 4, 2, s->tokens, s->dim);
    ada_value(shift, table, s->cross_scale_shift, 4, 3, s->tokens, s->dim);
    if (gate) ada_value(gate, table + 4 * s->dim, s->cross_gate, 1, 0,
                        s->tokens, s->dim);
}

static void run_feed_forward(stream *s) {
    float shift[MAX_ROWS * MAX_WIDTH], scale[MAX_ROWS * MAX_WIDTH];
    float gate[MAX_ROWS * MAX_WIDTH], scaled[MAX_ROWS * MAX_WIDTH];
    float inner[MAX_ROWS * MAX_WIDTH], projected[MAX_ROWS * MAX_WIDTH];
    size_t span = s->tokens * s->dim;

    ada_value(shift, s->scale_shift_table, s->timesteps, ADA_SLOTS, 3, s->tokens, s->dim);
    ada_value(scale, s->scale_shift_table, s->timesteps, ADA_SLOTS, 4, s->tokens, s->dim);
    ada_value(gate, s->scale_shift_table, s->timesteps, ADA_SLOTS, 5, s->tokens, s->dim);
    modulate(scaled, s->x, scale, shift, s->tokens, s->dim);
    /* Plain GELU at four times the width, not a gated pair: the projection's
     * output is the whole of the inner width. */
    linear_bias(inner, scaled, s->ff_in_w, s->ff_in_b, s->tokens, s->dim, s->ff);
    for (size_t index = 0; index < s->tokens * s->ff; index++)
        inner[index] = gelu_tanh_value(inner[index]);
    linear_bias(projected, inner, s->ff_out_w, s->ff_out_b, s->tokens,
                s->ff, s->dim);
    for (size_t index = 0; index < span; index++)
        s->x[index] += projected[index] * gate[index];
}

/* --------------------------------------------------------------- the GPU */

/* The same block again, out of the engine's existing kernels, to prove the
 * wiring rather than the arithmetic. Almost everything it needs was already
 * here: h3_gpu_adaln_bf16 is exactly rms_norm(x) * (1 + scale) + shift and
 * reaches LTX's per-token case through an identity row map and a unit norm
 * weight, so the AdaLN slices below are slot indices into one modulation
 * buffer rather than separate code.
 *
 * Storage is BF16 throughout, so this is compared against the same F32
 * reference at a looser bound; the gap is rounding, not structure. */

static uint16_t to_bf16(float value) {
    uint32_t bits;
    memcpy(&bits, &value, sizeof(bits));
    bits += UINT32_C(0x7fff) + ((bits >> 16) & 1u);
    return (uint16_t)(bits >> 16);
}

static float from_bf16(uint16_t value) {
    uint32_t bits = (uint32_t)value << 16;
    float result;
    memcpy(&result, &bits, sizeof(result));
    return result;
}

static h3_gpu_tensor *upload_bf16(h3_gpu *gpu, const float *values,
                                  size_t count) {
    uint16_t *rounded = malloc(count * sizeof(*rounded));
    require(rounded != NULL, "cannot allocate a BF16 staging buffer");
    for (size_t index = 0; index < count; index++)
        rounded[index] = to_bf16(values[index]);
    h3_gpu_tensor *tensor = h3_gpu_tensor_from_bf16(gpu, rounded, count);
    free(rounded);
    require(tensor != NULL, "cannot upload a BF16 tensor");
    return tensor;
}

static h3_gpu_tensor *upload_part(h3_gpu *gpu, const char *prefix,
                                  const char *suffix, size_t expected) {
    float *values = load_part(prefix, suffix, expected);
    h3_gpu_tensor *tensor = upload_bf16(gpu, values, expected);
    free(values);
    return tensor;
}

static void download_bf16(const h3_gpu_tensor *tensor, float *out,
                          size_t count) {
    uint16_t *raw = malloc(count * sizeof(*raw));
    require(raw != NULL, "cannot allocate a BF16 download buffer");
    require(h3_gpu_tensor_read_bf16(tensor, raw, count),
            "cannot read a GPU tensor");
    for (size_t index = 0; index < count; index++) out[index] = from_bf16(raw[index]);
    free(raw);
}

#define GPU_OP(call, what) \
    do { if (!(call)) { \
        fprintf(stderr, "FAIL: %s: %s\n", (what), h3_gpu_error(gpu)); \
        exit(1); \
    } } while (0)

typedef struct {
    size_t query_dim, context_dim, heads, head_dim, inner;
    h3_gpu_tensor *q_w, *q_b, *k_w, *k_b, *v_w, *v_b, *o_w, *o_b;
    h3_gpu_tensor *q_norm, *k_norm, *gate_w, *gate_b;
} gpu_attention;

static gpu_attention upload_attention(h3_gpu *gpu, const char *prefix,
                                      size_t query_dim, size_t context_dim,
                                      size_t heads, size_t head_dim) {
    gpu_attention a = {0};
    a.query_dim = query_dim;
    a.context_dim = context_dim;
    a.heads = heads;
    a.head_dim = head_dim;
    a.inner = heads * head_dim;
    a.q_w = upload_part(gpu, prefix, "to_q.weight", a.inner * query_dim);
    a.q_b = upload_part(gpu, prefix, "to_q.bias", a.inner);
    a.k_w = upload_part(gpu, prefix, "to_k.weight", a.inner * context_dim);
    a.k_b = upload_part(gpu, prefix, "to_k.bias", a.inner);
    a.v_w = upload_part(gpu, prefix, "to_v.weight", a.inner * context_dim);
    a.v_b = upload_part(gpu, prefix, "to_v.bias", a.inner);
    a.o_w = upload_part(gpu, prefix, "to_out.0.weight", query_dim * a.inner);
    a.o_b = upload_part(gpu, prefix, "to_out.0.bias", query_dim);
    a.q_norm = upload_part(gpu, prefix, "q_norm.weight", a.inner);
    a.k_norm = upload_part(gpu, prefix, "k_norm.weight", a.inner);
    a.gate_w = upload_part(gpu, prefix, "to_gate_logits.weight",
                           heads * query_dim);
    a.gate_b = upload_part(gpu, prefix, "to_gate_logits.bias", heads);
    return a;
}

static void free_gpu_attention(gpu_attention *a) {
    h3_gpu_tensor_free(a->q_w); h3_gpu_tensor_free(a->q_b);
    h3_gpu_tensor_free(a->k_w); h3_gpu_tensor_free(a->k_b);
    h3_gpu_tensor_free(a->v_w); h3_gpu_tensor_free(a->v_b);
    h3_gpu_tensor_free(a->o_w); h3_gpu_tensor_free(a->o_b);
    h3_gpu_tensor_free(a->q_norm); h3_gpu_tensor_free(a->k_norm);
    h3_gpu_tensor_free(a->gate_w); h3_gpu_tensor_free(a->gate_b);
}

/* Rotary tables are per head, so the stride between one head's slice and the
 * next is that slice's length. Passing zero here would share one table across
 * every head, which is Gemma's convention and not LTX's. */
static void gpu_attention_run(h3_gpu *gpu, h3_gpu_tensor *out,
                              const gpu_attention *a,
                              const h3_gpu_tensor *x, uint32_t rows_q,
                              const h3_gpu_tensor *context, uint32_t rows_kv,
                              const h3_gpu_tensor *q_cos,
                              const h3_gpu_tensor *q_sin,
                              const h3_gpu_tensor *k_cos,
                              const h3_gpu_tensor *k_sin) {
    h3_gpu_tensor *query = h3_gpu_tensor_new_bf16(gpu, (size_t)rows_q * a->inner);
    h3_gpu_tensor *key = h3_gpu_tensor_new_bf16(gpu, (size_t)rows_kv * a->inner);
    h3_gpu_tensor *value = h3_gpu_tensor_new_bf16(gpu, (size_t)rows_kv * a->inner);
    h3_gpu_tensor *joined = h3_gpu_tensor_new_bf16(gpu, (size_t)rows_q * a->inner);
    h3_gpu_tensor *logits = h3_gpu_tensor_new_bf16(gpu, (size_t)rows_q * a->heads);
    require(query && key && value && joined && logits,
            "cannot allocate attention scratch");

    GPU_OP(h3_gpu_linear_bf16(gpu, query, x, a->q_w, a->q_b, rows_q,
                              (uint32_t)a->query_dim, (uint32_t)a->inner),
           "query projection");
    GPU_OP(h3_gpu_linear_bf16(gpu, key, context, a->k_w, a->k_b, rows_kv,
                              (uint32_t)a->context_dim, (uint32_t)a->inner),
           "key projection");
    GPU_OP(h3_gpu_linear_bf16(gpu, value, context, a->v_w, a->v_b, rows_kv,
                              (uint32_t)a->context_dim, (uint32_t)a->inner),
           "value projection");
    /* Full inner width, not per head. */
    GPU_OP(h3_gpu_rms_norm_bf16(gpu, query, query, a->q_norm, rows_q,
                                (uint32_t)a->inner, BLOCK_EPS), "query norm");
    GPU_OP(h3_gpu_rms_norm_bf16(gpu, key, key, a->k_norm, rows_kv,
                                (uint32_t)a->inner, BLOCK_EPS), "key norm");
    if (q_cos) {
        uint32_t half = (uint32_t)a->head_dim / 2;
        GPU_OP(h3_gpu_rope_rows_bf16(gpu, query, q_cos, q_sin, rows_q,
                                     (uint32_t)a->heads, (uint32_t)a->head_dim,
                                     rows_q * half), "query rotation");
        GPU_OP(h3_gpu_rope_rows_bf16(gpu, key, k_cos ? k_cos : q_cos,
                                     k_sin ? k_sin : q_sin, rows_kv,
                                     (uint32_t)a->heads, (uint32_t)a->head_dim,
                                     rows_kv * half), "key rotation");
    }
    float scale = 1.0f / sqrtf((float)a->head_dim);
    GPU_OP(h3_gpu_sdpa_cross_bf16(gpu, joined, query, key, value, rows_q,
                                  rows_kv, (uint32_t)a->heads,
                                  (uint32_t)a->head_dim, scale), "attention");
    GPU_OP(h3_gpu_linear_bf16(gpu, logits, x, a->gate_w, a->gate_b, rows_q,
                              (uint32_t)a->query_dim, (uint32_t)a->heads),
           "gate logits");
    GPU_OP(h3_gpu_head_gate_bf16(gpu, joined, logits, rows_q,
                                 (uint32_t)a->heads, (uint32_t)a->head_dim),
           "head gating");
    GPU_OP(h3_gpu_linear_bf16(gpu, out, joined, a->o_w, a->o_b, rows_q,
                              (uint32_t)a->inner, (uint32_t)a->query_dim),
           "output projection");

    h3_gpu_tensor_free(query); h3_gpu_tensor_free(key);
    h3_gpu_tensor_free(value); h3_gpu_tensor_free(joined);
    h3_gpu_tensor_free(logits);
}

typedef struct {
    uint32_t dim, tokens, heads, head_dim, ff;
    gpu_attention self_attn, text_attn;
    h3_gpu_tensor *x, *pre, *context, *modulation, *ones, *row_map;
    h3_gpu_tensor *cross_modulation, *cross_gate_modulation;
    h3_gpu_tensor *ff_in_w, *ff_in_b, *ff_out_w, *ff_out_b;
    h3_gpu_tensor *rope_cos, *rope_sin, *cross_rope_cos, *cross_rope_sin;
    h3_gpu_tensor *branch, *scaled, *inner;
} gpu_stream;

static void gpu_self_and_text(h3_gpu *gpu, gpu_stream *s) {
    GPU_OP(h3_gpu_adaln_bf16(gpu, s->scaled, s->x, s->ones, s->modulation,
                             s->row_map, s->tokens, s->dim, ADA_SLOTS, 0, 1,
                             BLOCK_EPS), "self-attention modulation");
    gpu_attention_run(gpu, s->branch, &s->self_attn, s->scaled, s->tokens,
                      s->scaled, s->tokens, s->rope_cos, s->rope_sin,
                      NULL, NULL);
    GPU_OP(h3_gpu_gate_bf16(gpu, s->x, s->x, s->branch, s->modulation,
                            s->row_map, s->tokens, s->dim, ADA_SLOTS, 2),
           "self-attention residual");
    /* Slice 6..8. AdaLN normalises before modulating, which is exactly the
     * host's rms_norm followed by the affine, so the two collapse into one
     * call here rather than needing the intermediate. */
    GPU_OP(h3_gpu_adaln_bf16(gpu, s->scaled, s->x, s->ones, s->modulation,
                             s->row_map, s->tokens, s->dim, ADA_SLOTS, 6, 7,
                             BLOCK_EPS), "text cross-attention modulation");
    gpu_attention_run(gpu, s->branch, &s->text_attn, s->scaled, s->tokens,
                      s->context, TEXT_TOKENS, NULL, NULL, NULL, NULL);
    GPU_OP(h3_gpu_gate_bf16(gpu, s->x, s->x, s->branch, s->modulation,
                            s->row_map, s->tokens, s->dim, ADA_SLOTS, 8),
           "text cross-attention residual");
}

static void gpu_feed_forward(h3_gpu *gpu, gpu_stream *s) {
    GPU_OP(h3_gpu_adaln_bf16(gpu, s->scaled, s->x, s->ones, s->modulation,
                             s->row_map, s->tokens, s->dim, ADA_SLOTS, 3, 4,
                             BLOCK_EPS), "feed-forward modulation");
    GPU_OP(h3_gpu_linear_bf16(gpu, s->inner, s->scaled, s->ff_in_w, s->ff_in_b,
                              s->tokens, s->dim, s->ff), "feed-forward in");
    GPU_OP(h3_gpu_gelu_bf16(gpu, s->inner, s->inner, s->tokens * s->ff, 1),
           "feed-forward activation");
    GPU_OP(h3_gpu_linear_bf16(gpu, s->branch, s->inner, s->ff_out_w,
                              s->ff_out_b, s->tokens, s->ff, s->dim),
           "feed-forward out");
    GPU_OP(h3_gpu_gate_bf16(gpu, s->x, s->x, s->branch, s->modulation,
                            s->row_map, s->tokens, s->dim, ADA_SLOTS, 5),
           "feed-forward residual");
}

/* One stream's uploads. `table` is the block's static AdaLN rows and `stamp`
 * the per-token timestep embedding; their sum is the modulation buffer the
 * AdaLN and gate kernels read, so it is built once here rather than per use. */
static void gpu_stream_upload(h3_gpu *gpu, gpu_stream *s, const char *tag,
                              uint32_t dim, uint32_t tokens, uint32_t heads,
                              uint32_t head_dim, uint32_t ff,
                              const char *self_prefix, const char *text_prefix,
                              const char *table_name, const char *prompt_name,
                              const char *ff_prefix, int ff_bias) {
    char name[192];
    s->dim = dim; s->tokens = tokens; s->heads = heads;
    s->head_dim = head_dim; s->ff = ff;
    s->self_attn = upload_attention(gpu, self_prefix, dim, dim, heads, head_dim);
    s->text_attn = upload_attention(gpu, text_prefix, dim, dim, heads, head_dim);

    snprintf(name, sizeof(name), "input.%s_x", tag);
    float *x = load_f32(name, (size_t)tokens * dim);
    s->x = upload_bf16(gpu, x, (size_t)tokens * dim);
    s->pre = upload_bf16(gpu, x, (size_t)tokens * dim);
    free(x);

    /* The text side is modulated by the static table alone in this fixture, so
     * it is folded in at upload. That shortcut does not survive contact with
     * the released model, which adds a per-step prompt timestep on top; see
     * the header. */
    snprintf(name, sizeof(name), "input.%s_context", tag);
    float *context = load_f32(name, (size_t)TEXT_TOKENS * dim);
    float *prompt = load_f32(prompt_name, 2 * (size_t)dim);
    for (size_t token = 0; token < TEXT_TOKENS; token++)
        for (size_t d = 0; d < dim; d++)
            context[token * dim + d] = context[token * dim + d] *
                (1.0f + prompt[dim + d]) + prompt[d];
    s->context = upload_bf16(gpu, context, (size_t)TEXT_TOKENS * dim);
    free(context); free(prompt);

    snprintf(name, sizeof(name), "input.%s_timesteps", tag);
    float *stamp = load_f32(name, (size_t)tokens * ADA_SLOTS * dim);
    h3_gpu_tensor *stamp_gpu = upload_bf16(gpu, stamp, (size_t)tokens * ADA_SLOTS * dim);
    free(stamp);
    float *table = load_f32(table_name, ADA_SLOTS * (size_t)dim);
    h3_gpu_tensor *table_gpu = h3_gpu_tensor_from_f32(gpu, table, ADA_SLOTS * (size_t)dim);
    free(table);
    s->modulation = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * ADA_SLOTS * dim);
    require(s->modulation && stamp_gpu && table_gpu, "cannot allocate modulation");
    GPU_OP(h3_gpu_add_row_bf16(gpu, s->modulation, stamp_gpu, table_gpu,
                               tokens, ADA_SLOTS * dim), "modulation");
    h3_gpu_tensor_free(stamp_gpu); h3_gpu_tensor_free(table_gpu);

    snprintf(name, sizeof(name), "%snet.0.proj.weight", ff_prefix);
    s->ff_in_w = upload_part(gpu, "", name, (size_t)ff * dim);
    snprintf(name, sizeof(name), "%snet.2.weight", ff_prefix);
    s->ff_out_w = upload_part(gpu, "", name, (size_t)dim * ff);
    if (ff_bias) {
        snprintf(name, sizeof(name), "%snet.0.proj.bias", ff_prefix);
        s->ff_in_b = upload_part(gpu, "", name, ff);
        snprintf(name, sizeof(name), "%snet.2.bias", ff_prefix);
        s->ff_out_b = upload_part(gpu, "", name, dim);
    }

    snprintf(name, sizeof(name), "input.%s_rope_cos", tag);
    float *cos_table = load_f32(name, (size_t)heads * tokens * (head_dim / 2));
    s->rope_cos = h3_gpu_tensor_from_f32(gpu, cos_table,
                                         (size_t)heads * tokens * (head_dim / 2));
    free(cos_table);
    snprintf(name, sizeof(name), "input.%s_rope_sin", tag);
    float *sin_table = load_f32(name, (size_t)heads * tokens * (head_dim / 2));
    s->rope_sin = h3_gpu_tensor_from_f32(gpu, sin_table,
                                         (size_t)heads * tokens * (head_dim / 2));
    free(sin_table);
    /* The cross-modal tables are at the audio head width in both streams. */
    snprintf(name, sizeof(name), "input.%s_cross_rope_cos", tag);
    float *cross_cos = load_f32(name, (size_t)AUDIO_HEADS * tokens * (AUDIO_HEAD / 2));
    s->cross_rope_cos = h3_gpu_tensor_from_f32(gpu, cross_cos,
                                               (size_t)AUDIO_HEADS * tokens * (AUDIO_HEAD / 2));
    free(cross_cos);
    snprintf(name, sizeof(name), "input.%s_cross_rope_sin", tag);
    float *cross_sin = load_f32(name, (size_t)AUDIO_HEADS * tokens * (AUDIO_HEAD / 2));
    s->cross_rope_sin = h3_gpu_tensor_from_f32(gpu, cross_sin,
                                               (size_t)AUDIO_HEADS * tokens * (AUDIO_HEAD / 2));
    free(cross_sin);

    uint32_t *identity = malloc(tokens * sizeof(*identity));
    require(identity != NULL, "cannot allocate a row map");
    for (uint32_t row = 0; row < tokens; row++) identity[row] = row;
    s->row_map = h3_gpu_tensor_from_u32(gpu, identity, tokens);
    free(identity);
    float *ones = malloc(dim * sizeof(*ones));
    require(ones != NULL, "cannot allocate a unit norm weight");
    for (uint32_t d = 0; d < dim; d++) ones[d] = 1.0f;
    s->ones = upload_bf16(gpu, ones, dim);
    free(ones);

    s->branch = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * dim);
    s->scaled = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * dim);
    s->inner = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * ff);
    s->cross_modulation = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * 4 * dim);
    s->cross_gate_modulation = h3_gpu_tensor_new_bf16(gpu, (size_t)tokens * dim);
    require(s->branch && s->scaled && s->inner && s->cross_modulation &&
            s->cross_gate_modulation && s->row_map, "cannot allocate stream scratch");

    /* The cross-modal tables are five rows: four of scale and shift, one of
     * gate, each with its own timestep width. */
    snprintf(name, sizeof(name), "block.scale_shift_table_a2v_ca_%s", tag);
    float *cross_table = load_f32(name, 5 * (size_t)dim);
    snprintf(name, sizeof(name), "input.%s_cross_scale_shift", tag);
    float *cross_stamp = load_f32(name, (size_t)tokens * 4 * dim);
    h3_gpu_tensor *cross_stamp_gpu = upload_bf16(gpu, cross_stamp, (size_t)tokens * 4 * dim);
    h3_gpu_tensor *cross_table_gpu = h3_gpu_tensor_from_f32(gpu, cross_table, 4 * (size_t)dim);
    GPU_OP(h3_gpu_add_row_bf16(gpu, s->cross_modulation, cross_stamp_gpu,
                               cross_table_gpu, tokens, 4 * dim),
           "cross-modal modulation");
    snprintf(name, sizeof(name), "input.%s_cross_gate", tag);
    float *gate_stamp = load_f32(name, (size_t)tokens * dim);
    h3_gpu_tensor *gate_stamp_gpu = upload_bf16(gpu, gate_stamp, (size_t)tokens * dim);
    h3_gpu_tensor *gate_table_gpu = h3_gpu_tensor_from_f32(gpu, cross_table + 4 * dim, dim);
    GPU_OP(h3_gpu_add_row_bf16(gpu, s->cross_gate_modulation, gate_stamp_gpu,
                               gate_table_gpu, tokens, dim), "cross-modal gate");
    h3_gpu_tensor_free(cross_stamp_gpu); h3_gpu_tensor_free(cross_table_gpu);
    h3_gpu_tensor_free(gate_stamp_gpu); h3_gpu_tensor_free(gate_table_gpu);
    free(cross_table); free(cross_stamp); free(gate_stamp);
}

static void run_gpu_block(h3_gpu *gpu, float *video_out, float *audio_out) {
    gpu_stream video = {0}, audio = {0};

    GPU_OP(h3_gpu_begin(gpu), "begin uploads");
    gpu_stream_upload(gpu, &video, "video", VIDEO_DIM, VIDEO_TOKENS,
                      VIDEO_HEADS, VIDEO_HEAD, VIDEO_FF, "attn1.", "attn2.",
                      "block.scale_shift_table", "block.prompt_scale_shift_table",
                      "ff.", 0);
    gpu_stream_upload(gpu, &audio, "audio", AUDIO_DIM, AUDIO_TOKENS,
                      AUDIO_HEADS, AUDIO_HEAD, AUDIO_FF, "audio_attn1.",
                      "audio_attn2.", "block.audio_scale_shift_table",
                      "block.audio_prompt_scale_shift_table", "audio_ff.", 1);
    gpu_attention a2v = upload_attention(gpu, "audio_to_video_attn.",
                                         VIDEO_DIM, AUDIO_DIM, AUDIO_HEADS,
                                         AUDIO_HEAD);
    gpu_attention v2a = upload_attention(gpu, "video_to_audio_attn.",
                                         AUDIO_DIM, VIDEO_DIM, AUDIO_HEADS,
                                         AUDIO_HEAD);
    h3_gpu_tensor *video_scaled = h3_gpu_tensor_new_bf16(gpu, VIDEO_TOKENS * VIDEO_DIM);
    h3_gpu_tensor *audio_scaled = h3_gpu_tensor_new_bf16(gpu, AUDIO_TOKENS * AUDIO_DIM);
    require(video_scaled && audio_scaled, "cannot allocate cross-modal scratch");

    gpu_self_and_text(gpu, &video);
    gpu_self_and_text(gpu, &audio);

    /* Snapshot both streams before either direction runs. */
    GPU_OP(h3_gpu_copy_bf16(gpu, video.pre, 0, video.x, 0,
                            VIDEO_TOKENS * VIDEO_DIM), "video snapshot");
    GPU_OP(h3_gpu_copy_bf16(gpu, audio.pre, 0, audio.x, 0,
                            AUDIO_TOKENS * AUDIO_DIM), "audio snapshot");

    /* Audio to video. Slots 0 and 1 of the cross-modal table, and note that
     * this one is scale before shift where the slices above are shift first. */
    GPU_OP(h3_gpu_adaln_bf16(gpu, video_scaled, video.pre, video.ones,
                             video.cross_modulation, video.row_map,
                             VIDEO_TOKENS, VIDEO_DIM, 4, 1, 0, BLOCK_EPS),
           "a2v video modulation");
    GPU_OP(h3_gpu_adaln_bf16(gpu, audio_scaled, audio.pre, audio.ones,
                             audio.cross_modulation, audio.row_map,
                             AUDIO_TOKENS, AUDIO_DIM, 4, 1, 0, BLOCK_EPS),
           "a2v audio modulation");
    gpu_attention_run(gpu, video.branch, &a2v, video_scaled, VIDEO_TOKENS,
                      audio_scaled, AUDIO_TOKENS,
                      video.cross_rope_cos, video.cross_rope_sin,
                      audio.cross_rope_cos, audio.cross_rope_sin);
    GPU_OP(h3_gpu_gate_bf16(gpu, video.x, video.x, video.branch,
                            video.cross_gate_modulation, video.row_map,
                            VIDEO_TOKENS, VIDEO_DIM, 1, 0), "a2v residual");

    /* Video to audio, slots 2 and 3, both streams read from the snapshot. */
    GPU_OP(h3_gpu_adaln_bf16(gpu, audio_scaled, audio.pre, audio.ones,
                             audio.cross_modulation, audio.row_map,
                             AUDIO_TOKENS, AUDIO_DIM, 4, 3, 2, BLOCK_EPS),
           "v2a audio modulation");
    GPU_OP(h3_gpu_adaln_bf16(gpu, video_scaled, video.pre, video.ones,
                             video.cross_modulation, video.row_map,
                             VIDEO_TOKENS, VIDEO_DIM, 4, 3, 2, BLOCK_EPS),
           "v2a video modulation");
    gpu_attention_run(gpu, audio.branch, &v2a, audio_scaled, AUDIO_TOKENS,
                      video_scaled, VIDEO_TOKENS,
                      audio.cross_rope_cos, audio.cross_rope_sin,
                      video.cross_rope_cos, video.cross_rope_sin);
    GPU_OP(h3_gpu_gate_bf16(gpu, audio.x, audio.x, audio.branch,
                            audio.cross_gate_modulation, audio.row_map,
                            AUDIO_TOKENS, AUDIO_DIM, 1, 0), "v2a residual");

    gpu_feed_forward(gpu, &video);
    gpu_feed_forward(gpu, &audio);
    GPU_OP(h3_gpu_submit(gpu), "submit the block");

    download_bf16(video.x, video_out, VIDEO_TOKENS * VIDEO_DIM);
    download_bf16(audio.x, audio_out, AUDIO_TOKENS * AUDIO_DIM);

    free_gpu_attention(&a2v); free_gpu_attention(&v2a);
    free_gpu_attention(&video.self_attn); free_gpu_attention(&video.text_attn);
    free_gpu_attention(&audio.self_attn); free_gpu_attention(&audio.text_attn);
    h3_gpu_tensor_free(video_scaled); h3_gpu_tensor_free(audio_scaled);
}

int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "usage: %s FIXTURE.safetensors\n", argv[0]);
        return 2;
    }
    char error[512];
    store = h3_weight_store_open(argv[1], error, sizeof(error));
    if (!store) {
        fprintf(stderr, "FAIL: cannot open the fixture: %s\n", error);
        return 1;
    }

    printf("LTX-2.5 dual-stream DiT block against its own implementation:\n");

    stream video = {
        .dim = VIDEO_DIM, .tokens = VIDEO_TOKENS,
        .heads = VIDEO_HEADS, .head_dim = VIDEO_HEAD, .ff = VIDEO_FF,
        .self_attn = load_attention("attn1.", VIDEO_DIM, VIDEO_DIM,
                                    VIDEO_HEADS, VIDEO_HEAD),
        .text_attn = load_attention("attn2.", VIDEO_DIM, VIDEO_DIM,
                                    VIDEO_HEADS, VIDEO_HEAD),
        .scale_shift_table = load_f32("block.scale_shift_table",
                                      ADA_SLOTS * VIDEO_DIM),
        .prompt_scale_shift = load_f32("block.prompt_scale_shift_table",
                                       2 * VIDEO_DIM),
        /* The video feed-forward carries no bias; the audio one does. */
        .ff_in_w = load_f32("block.ff.net.0.proj.weight", VIDEO_FF * VIDEO_DIM),
        .ff_in_b = NULL,
        .ff_out_w = load_f32("block.ff.net.2.weight", VIDEO_DIM * VIDEO_FF),
        .ff_out_b = NULL,
        .x = load_f32("input.video_x", VIDEO_TOKENS * VIDEO_DIM),
        .context = load_f32("input.video_context", TEXT_TOKENS * VIDEO_DIM),
        .timesteps = load_f32("input.video_timesteps",
                              VIDEO_TOKENS * ADA_SLOTS * VIDEO_DIM),
        .cross_scale_shift = load_f32("input.video_cross_scale_shift",
                                      VIDEO_TOKENS * 4 * VIDEO_DIM),
        .cross_gate = load_f32("input.video_cross_gate",
                               VIDEO_TOKENS * VIDEO_DIM),
        .rope_cos = load_f32("input.video_rope_cos",
                             VIDEO_HEADS * VIDEO_TOKENS * (VIDEO_HEAD / 2)),
        .rope_sin = load_f32("input.video_rope_sin",
                             VIDEO_HEADS * VIDEO_TOKENS * (VIDEO_HEAD / 2)),
        .cross_rope_cos = load_f32("input.video_cross_rope_cos",
                                   AUDIO_HEADS * VIDEO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_sin = load_f32("input.video_cross_rope_sin",
                                   AUDIO_HEADS * VIDEO_TOKENS * (AUDIO_HEAD / 2)),
    };

    stream audio = {
        .dim = AUDIO_DIM, .tokens = AUDIO_TOKENS,
        .heads = AUDIO_HEADS, .head_dim = AUDIO_HEAD, .ff = AUDIO_FF,
        .self_attn = load_attention("audio_attn1.", AUDIO_DIM, AUDIO_DIM,
                                    AUDIO_HEADS, AUDIO_HEAD),
        .text_attn = load_attention("audio_attn2.", AUDIO_DIM, AUDIO_DIM,
                                    AUDIO_HEADS, AUDIO_HEAD),
        .scale_shift_table = load_f32("block.audio_scale_shift_table",
                                      ADA_SLOTS * AUDIO_DIM),
        .prompt_scale_shift = load_f32("block.audio_prompt_scale_shift_table",
                                       2 * AUDIO_DIM),
        .ff_in_w = load_f32("block.audio_ff.net.0.proj.weight",
                            AUDIO_FF * AUDIO_DIM),
        .ff_in_b = load_f32("block.audio_ff.net.0.proj.bias", AUDIO_FF),
        .ff_out_w = load_f32("block.audio_ff.net.2.weight",
                             AUDIO_DIM * AUDIO_FF),
        .ff_out_b = load_f32("block.audio_ff.net.2.bias", AUDIO_DIM),
        .x = load_f32("input.audio_x", AUDIO_TOKENS * AUDIO_DIM),
        .context = load_f32("input.audio_context", TEXT_TOKENS * AUDIO_DIM),
        .timesteps = load_f32("input.audio_timesteps",
                              AUDIO_TOKENS * ADA_SLOTS * AUDIO_DIM),
        .cross_scale_shift = load_f32("input.audio_cross_scale_shift",
                                      AUDIO_TOKENS * 4 * AUDIO_DIM),
        .cross_gate = load_f32("input.audio_cross_gate",
                               AUDIO_TOKENS * AUDIO_DIM),
        .rope_cos = load_f32("input.audio_rope_cos",
                             AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .rope_sin = load_f32("input.audio_rope_sin",
                             AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_cos = load_f32("input.audio_cross_rope_cos",
                                   AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
        .cross_rope_sin = load_f32("input.audio_cross_rope_sin",
                                   AUDIO_HEADS * AUDIO_TOKENS * (AUDIO_HEAD / 2)),
    };

    /* Both cross-modal attentions run at the audio stream's head width, in
     * both directions: video queries are projected down and the result back
     * up, so the video width appears only at the ends. */
    attention a2v = load_attention("audio_to_video_attn.", VIDEO_DIM, AUDIO_DIM,
                                   AUDIO_HEADS, AUDIO_HEAD);
    attention v2a = load_attention("video_to_audio_attn.", AUDIO_DIM, VIDEO_DIM,
                                   AUDIO_HEADS, AUDIO_HEAD);
    float *a2v_video_table = load_f32("block.scale_shift_table_a2v_ca_video",
                                      5 * VIDEO_DIM);
    float *a2v_audio_table = load_f32("block.scale_shift_table_a2v_ca_audio",
                                      5 * AUDIO_DIM);

    run_self_and_text(&video);
    run_self_and_text(&audio);

    /* Snapshot both streams before either direction runs, so the result does
     * not depend on which direction is computed first. Only one of the four
     * reads below can actually differ from the live state -- video-to-audio's
     * video keys and values, since audio-to-video has by then changed the
     * video stream and nothing has changed the audio one. */
    float video_pre[VIDEO_TOKENS * VIDEO_DIM];
    float audio_pre[AUDIO_TOKENS * AUDIO_DIM];
    memcpy(video_pre, video.x, sizeof(video_pre));
    memcpy(audio_pre, audio.x, sizeof(audio_pre));

    {
        float scale[MAX_ROWS * MAX_WIDTH], shift[MAX_ROWS * MAX_WIDTH];
        float gate[MAX_ROWS * MAX_WIDTH];
        float video_scaled[VIDEO_TOKENS * VIDEO_DIM];
        float audio_scaled[AUDIO_TOKENS * AUDIO_DIM];
        float out[VIDEO_TOKENS * VIDEO_DIM];

        cross_ada(scale, shift, gate, &video, a2v_video_table);
        modulate(video_scaled, video_pre, scale, shift, VIDEO_TOKENS, VIDEO_DIM);
        cross_ada(scale, shift, NULL, &audio, a2v_audio_table);
        modulate(audio_scaled, audio_pre, scale, shift, AUDIO_TOKENS, AUDIO_DIM);
        run_attention(out, &a2v, video_scaled, VIDEO_TOKENS,
                      audio_scaled, AUDIO_TOKENS,
                      video.cross_rope_cos, video.cross_rope_sin,
                      audio.cross_rope_cos, audio.cross_rope_sin);
        for (size_t index = 0; index < VIDEO_TOKENS * VIDEO_DIM; index++)
            video.x[index] += out[index] * gate[index];
    }

    {
        float scale[MAX_ROWS * MAX_WIDTH], shift[MAX_ROWS * MAX_WIDTH];
        float gate[MAX_ROWS * MAX_WIDTH];
        float video_scaled[VIDEO_TOKENS * VIDEO_DIM];
        float audio_scaled[AUDIO_TOKENS * AUDIO_DIM];
        float out[AUDIO_TOKENS * AUDIO_DIM];

        cross_ada_second(scale, shift, gate, &audio, a2v_audio_table);
        modulate(audio_scaled, audio_pre, scale, shift, AUDIO_TOKENS, AUDIO_DIM);
        cross_ada_second(scale, shift, NULL, &video, a2v_video_table);
        modulate(video_scaled, video_pre, scale, shift, VIDEO_TOKENS, VIDEO_DIM);
        run_attention(out, &v2a, audio_scaled, AUDIO_TOKENS,
                      video_scaled, VIDEO_TOKENS,
                      audio.cross_rope_cos, audio.cross_rope_sin,
                      video.cross_rope_cos, video.cross_rope_sin);
        for (size_t index = 0; index < AUDIO_TOKENS * AUDIO_DIM; index++)
            audio.x[index] += out[index] * gate[index];
    }

    run_feed_forward(&video);
    run_feed_forward(&audio);

    float *expected_video = load_f32("reference.video_out",
                                     VIDEO_TOKENS * VIDEO_DIM);
    float *expected_audio = load_f32("reference.audio_out",
                                     AUDIO_TOKENS * AUDIO_DIM);
    /* Eight attentions and two feed-forwards of F32 accumulation land at
     * 1.2e-06 on values around one, so 1e-05 leaves room for a different
     * libm without letting anything structural through. */
    compare("video stream", video.x, expected_video,
            VIDEO_TOKENS * VIDEO_DIM, 1e-5f);
    compare("audio stream", audio.x, expected_audio,
            AUDIO_TOKENS * AUDIO_DIM, 1e-5f);

    /* The same block out of the engine's kernels, at BF16 storage. */
    char gpu_error[512];
    if (h3_gpu_prepare("h3_shaders.metal", gpu_error, sizeof(gpu_error))) {
        h3_gpu *gpu = h3_gpu_create("h3_shaders.metal", gpu_error,
                                    sizeof(gpu_error));
        require(gpu != NULL, "cannot create a GPU context");
        float gpu_video[VIDEO_TOKENS * VIDEO_DIM];
        float gpu_audio[AUDIO_TOKENS * AUDIO_DIM];
        run_gpu_block(gpu, gpu_video, gpu_audio);
        /* BF16 storage sets this floor, not the wiring: eight attentions and
         * two feed-forwards accumulate rounding against an F32 reference.
         *
         * The floor is why the two comparisons are not redundant. Swapping
         * the GELU flavour moves this by 1.4e-03, which sits under the bound
         * and so passes here, while the host reference above catches the same
         * change at 5.9e-04 against its own 1e-05. Structural mistakes clear
         * the bound easily -- the checked mutations land between 7e-02 and
         * 3.6e+00 -- but anything at rounding scale is the host's to catch. */
        compare("video stream on the GPU", gpu_video, expected_video,
                VIDEO_TOKENS * VIDEO_DIM, 3e-2f);
        compare("audio stream on the GPU", gpu_audio, expected_audio,
                AUDIO_TOKENS * AUDIO_DIM, 3e-2f);
        h3_gpu_free(gpu);
    } else {
        printf("  --  no GPU here, host reference only (%s)\n", gpu_error);
    }

    free_attention(&video.self_attn); free_attention(&video.text_attn);
    free_attention(&audio.self_attn); free_attention(&audio.text_attn);
    free_attention(&a2v); free_attention(&v2a);
    free(a2v_video_table); free(a2v_audio_table);
    free(expected_video); free(expected_audio);
    h3_weight_store_free(store);

    if (failures) {
        fprintf(stderr, "\n%d block comparisons failed\n", failures);
        return 1;
    }
    printf("ok: the dual-stream block reproduces LTX-2.5's own outputs, "
           "both couplings included\n");
    return 0;
}
